/// The proto definitions for robot
/// {@category Protobuf Definitions}
library viam_protos.robot.robot;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/robot/v1/robot.pb.dart';
export '../../../src/gen/robot/v1/robot.pbjson.dart';
export '../../../src/gen/robot/v1/robot.pbgrpc.dart';
export '../../../src/gen/robot/v1/robot.pbenum.dart';
