// Mocks generated by Mockito 5.4.2 from annotations
// in viam_sdk/test/unit_test/mocks/service_clients_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:grpc/service_api.dart' as _i4;
import 'package:grpc/src/client/call.dart' as _i3;
import 'package:grpc/src/client/channel.dart' as _i5;
import 'package:grpc/src/client/connection.dart' as _i2;
import 'package:grpc/src/client/method.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:viam_sdk/src/gen/app/data/v1/data.pb.dart' as _i13;
import 'package:viam_sdk/src/gen/app/data/v1/data.pbgrpc.dart' as _i12;
import 'package:viam_sdk/src/gen/app/v1/app.pb.dart' as _i11;
import 'package:viam_sdk/src/gen/app/v1/app.pbgrpc.dart' as _i10;
import 'package:viam_sdk/src/gen/robot/v1/robot.pb.dart' as _i9;
import 'package:viam_sdk/src/gen/robot/v1/robot.pbgrpc.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClientConnection_0 extends _i1.SmartFake
    implements _i2.ClientConnection {
  _FakeClientConnection_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClientCall_1<Q1, R1> extends _i1.SmartFake
    implements _i3.ClientCall<Q1, R1> {
  _FakeClientCall_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponseFuture_2<R> extends _i1.SmartFake
    implements _i4.ResponseFuture<R> {
  _FakeResponseFuture_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponseStream_3<R> extends _i1.SmartFake
    implements _i4.ResponseStream<R> {
  _FakeResponseStream_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ClientChannelBase].
///
/// See the documentation for Mockito's code generation for more information.
class MockClientChannelBase extends _i1.Mock implements _i5.ClientChannelBase {
  @override
  _i6.Stream<_i2.ConnectionState> get onConnectionStateChanged =>
      (super.noSuchMethod(
        Invocation.getter(#onConnectionStateChanged),
        returnValue: _i6.Stream<_i2.ConnectionState>.empty(),
        returnValueForMissingStub: _i6.Stream<_i2.ConnectionState>.empty(),
      ) as _i6.Stream<_i2.ConnectionState>);
  @override
  _i6.Future<void> shutdown() => (super.noSuchMethod(
        Invocation.method(
          #shutdown,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
  @override
  _i6.Future<void> terminate() => (super.noSuchMethod(
        Invocation.method(
          #terminate,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
  @override
  _i2.ClientConnection createConnection() => (super.noSuchMethod(
        Invocation.method(
          #createConnection,
          [],
        ),
        returnValue: _FakeClientConnection_0(
          this,
          Invocation.method(
            #createConnection,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeClientConnection_0(
          this,
          Invocation.method(
            #createConnection,
            [],
          ),
        ),
      ) as _i2.ClientConnection);
  @override
  _i6.Future<_i2.ClientConnection> getConnection() => (super.noSuchMethod(
        Invocation.method(
          #getConnection,
          [],
        ),
        returnValue:
            _i6.Future<_i2.ClientConnection>.value(_FakeClientConnection_0(
          this,
          Invocation.method(
            #getConnection,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.ClientConnection>.value(_FakeClientConnection_0(
          this,
          Invocation.method(
            #getConnection,
            [],
          ),
        )),
      ) as _i6.Future<_i2.ClientConnection>);
  @override
  _i3.ClientCall<Q, R> createCall<Q, R>(
    _i7.ClientMethod<Q, R>? method,
    _i6.Stream<Q>? requests,
    _i3.CallOptions? options,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCall,
          [
            method,
            requests,
            options,
          ],
        ),
        returnValue: _FakeClientCall_1<Q, R>(
          this,
          Invocation.method(
            #createCall,
            [
              method,
              requests,
              options,
            ],
          ),
        ),
        returnValueForMissingStub: _FakeClientCall_1<Q, R>(
          this,
          Invocation.method(
            #createCall,
            [
              method,
              requests,
              options,
            ],
          ),
        ),
      ) as _i3.ClientCall<Q, R>);
}

/// A class which mocks [RobotServiceClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockRobotServiceClient extends _i1.Mock
    implements _i8.RobotServiceClient {
  @override
  _i4.ResponseFuture<_i9.GetOperationsResponse> getOperations(
    _i9.GetOperationsRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOperations,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i9.GetOperationsResponse>(
          this,
          Invocation.method(
            #getOperations,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i9.GetOperationsResponse>(
          this,
          Invocation.method(
            #getOperations,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i9.GetOperationsResponse>);
  @override
  _i4.ResponseFuture<_i9.GetSessionsResponse> getSessions(
    _i9.GetSessionsRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSessions,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i9.GetSessionsResponse>(
          this,
          Invocation.method(
            #getSessions,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i9.GetSessionsResponse>(
          this,
          Invocation.method(
            #getSessions,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i9.GetSessionsResponse>);
  @override
  _i4.ResponseFuture<_i9.ResourceNamesResponse> resourceNames(
    _i9.ResourceNamesRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resourceNames,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i9.ResourceNamesResponse>(
          this,
          Invocation.method(
            #resourceNames,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i9.ResourceNamesResponse>(
          this,
          Invocation.method(
            #resourceNames,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i9.ResourceNamesResponse>);
  @override
  _i4.ResponseFuture<_i9.ResourceRPCSubtypesResponse> resourceRPCSubtypes(
    _i9.ResourceRPCSubtypesRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resourceRPCSubtypes,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i9.ResourceRPCSubtypesResponse>(
          this,
          Invocation.method(
            #resourceRPCSubtypes,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i9.ResourceRPCSubtypesResponse>(
          this,
          Invocation.method(
            #resourceRPCSubtypes,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i9.ResourceRPCSubtypesResponse>);
  @override
  _i4.ResponseFuture<_i9.CancelOperationResponse> cancelOperation(
    _i9.CancelOperationRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelOperation,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i9.CancelOperationResponse>(
          this,
          Invocation.method(
            #cancelOperation,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i9.CancelOperationResponse>(
          this,
          Invocation.method(
            #cancelOperation,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i9.CancelOperationResponse>);
  @override
  _i4.ResponseFuture<_i9.BlockForOperationResponse> blockForOperation(
    _i9.BlockForOperationRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #blockForOperation,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i9.BlockForOperationResponse>(
          this,
          Invocation.method(
            #blockForOperation,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i9.BlockForOperationResponse>(
          this,
          Invocation.method(
            #blockForOperation,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i9.BlockForOperationResponse>);
  @override
  _i4.ResponseFuture<_i9.DiscoverComponentsResponse> discoverComponents(
    _i9.DiscoverComponentsRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverComponents,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i9.DiscoverComponentsResponse>(
          this,
          Invocation.method(
            #discoverComponents,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i9.DiscoverComponentsResponse>(
          this,
          Invocation.method(
            #discoverComponents,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i9.DiscoverComponentsResponse>);
  @override
  _i4.ResponseFuture<_i9.FrameSystemConfigResponse> frameSystemConfig(
    _i9.FrameSystemConfigRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #frameSystemConfig,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i9.FrameSystemConfigResponse>(
          this,
          Invocation.method(
            #frameSystemConfig,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i9.FrameSystemConfigResponse>(
          this,
          Invocation.method(
            #frameSystemConfig,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i9.FrameSystemConfigResponse>);
  @override
  _i4.ResponseFuture<_i9.TransformPoseResponse> transformPose(
    _i9.TransformPoseRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transformPose,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i9.TransformPoseResponse>(
          this,
          Invocation.method(
            #transformPose,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i9.TransformPoseResponse>(
          this,
          Invocation.method(
            #transformPose,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i9.TransformPoseResponse>);
  @override
  _i4.ResponseFuture<_i9.TransformPCDResponse> transformPCD(
    _i9.TransformPCDRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transformPCD,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i9.TransformPCDResponse>(
          this,
          Invocation.method(
            #transformPCD,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i9.TransformPCDResponse>(
          this,
          Invocation.method(
            #transformPCD,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i9.TransformPCDResponse>);
  @override
  _i4.ResponseFuture<_i9.GetStatusResponse> getStatus(
    _i9.GetStatusRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStatus,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i9.GetStatusResponse>(
          this,
          Invocation.method(
            #getStatus,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i9.GetStatusResponse>(
          this,
          Invocation.method(
            #getStatus,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i9.GetStatusResponse>);
  @override
  _i4.ResponseStream<_i9.StreamStatusResponse> streamStatus(
    _i9.StreamStatusRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamStatus,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseStream_3<_i9.StreamStatusResponse>(
          this,
          Invocation.method(
            #streamStatus,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseStream_3<_i9.StreamStatusResponse>(
          this,
          Invocation.method(
            #streamStatus,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseStream<_i9.StreamStatusResponse>);
  @override
  _i4.ResponseFuture<_i9.StopAllResponse> stopAll(
    _i9.StopAllRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #stopAll,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i9.StopAllResponse>(
          this,
          Invocation.method(
            #stopAll,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i9.StopAllResponse>(
          this,
          Invocation.method(
            #stopAll,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i9.StopAllResponse>);
  @override
  _i4.ResponseFuture<_i9.StartSessionResponse> startSession(
    _i9.StartSessionRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startSession,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i9.StartSessionResponse>(
          this,
          Invocation.method(
            #startSession,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i9.StartSessionResponse>(
          this,
          Invocation.method(
            #startSession,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i9.StartSessionResponse>);
  @override
  _i4.ResponseFuture<_i9.SendSessionHeartbeatResponse> sendSessionHeartbeat(
    _i9.SendSessionHeartbeatRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendSessionHeartbeat,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i9.SendSessionHeartbeatResponse>(
          this,
          Invocation.method(
            #sendSessionHeartbeat,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i9.SendSessionHeartbeatResponse>(
          this,
          Invocation.method(
            #sendSessionHeartbeat,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i9.SendSessionHeartbeatResponse>);
  @override
  _i3.ClientCall<Q, R> $createCall<Q, R>(
    _i7.ClientMethod<Q, R>? method,
    _i6.Stream<Q>? requests, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createCall,
          [
            method,
            requests,
          ],
          {#options: options},
        ),
        returnValue: _FakeClientCall_1<Q, R>(
          this,
          Invocation.method(
            #$createCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeClientCall_1<Q, R>(
          this,
          Invocation.method(
            #$createCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
      ) as _i3.ClientCall<Q, R>);
  @override
  _i4.ResponseFuture<R> $createUnaryCall<Q, R>(
    _i7.ClientMethod<Q, R>? method,
    Q? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createUnaryCall,
          [
            method,
            request,
          ],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<R>(
          this,
          Invocation.method(
            #$createUnaryCall,
            [
              method,
              request,
            ],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<R>(
          this,
          Invocation.method(
            #$createUnaryCall,
            [
              method,
              request,
            ],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<R>);
  @override
  _i4.ResponseStream<R> $createStreamingCall<Q, R>(
    _i7.ClientMethod<Q, R>? method,
    _i6.Stream<Q>? requests, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createStreamingCall,
          [
            method,
            requests,
          ],
          {#options: options},
        ),
        returnValue: _FakeResponseStream_3<R>(
          this,
          Invocation.method(
            #$createStreamingCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseStream_3<R>(
          this,
          Invocation.method(
            #$createStreamingCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseStream<R>);
}

/// A class which mocks [AppServiceClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppServiceClient extends _i1.Mock implements _i10.AppServiceClient {
  @override
  _i4.ResponseFuture<_i11.GetUserIDByEmailResponse> getUserIDByEmail(
    _i11.GetUserIDByEmailRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserIDByEmail,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.GetUserIDByEmailResponse>(
          this,
          Invocation.method(
            #getUserIDByEmail,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.GetUserIDByEmailResponse>(
          this,
          Invocation.method(
            #getUserIDByEmail,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.GetUserIDByEmailResponse>);
  @override
  _i4.ResponseFuture<_i11.CreateOrganizationResponse> createOrganization(
    _i11.CreateOrganizationRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrganization,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.CreateOrganizationResponse>(
          this,
          Invocation.method(
            #createOrganization,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.CreateOrganizationResponse>(
          this,
          Invocation.method(
            #createOrganization,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.CreateOrganizationResponse>);
  @override
  _i4.ResponseFuture<_i11.ListOrganizationsResponse> listOrganizations(
    _i11.ListOrganizationsRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listOrganizations,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.ListOrganizationsResponse>(
          this,
          Invocation.method(
            #listOrganizations,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.ListOrganizationsResponse>(
          this,
          Invocation.method(
            #listOrganizations,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.ListOrganizationsResponse>);
  @override
  _i4.ResponseFuture<_i11.ListOrganizationsByUserResponse>
      listOrganizationsByUser(
    _i11.ListOrganizationsByUserRequest? request, {
    _i3.CallOptions? options,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #listOrganizationsByUser,
              [request],
              {#options: options},
            ),
            returnValue:
                _FakeResponseFuture_2<_i11.ListOrganizationsByUserResponse>(
              this,
              Invocation.method(
                #listOrganizationsByUser,
                [request],
                {#options: options},
              ),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_2<_i11.ListOrganizationsByUserResponse>(
              this,
              Invocation.method(
                #listOrganizationsByUser,
                [request],
                {#options: options},
              ),
            ),
          ) as _i4.ResponseFuture<_i11.ListOrganizationsByUserResponse>);
  @override
  _i4.ResponseFuture<_i11.GetOrganizationResponse> getOrganization(
    _i11.GetOrganizationRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrganization,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.GetOrganizationResponse>(
          this,
          Invocation.method(
            #getOrganization,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.GetOrganizationResponse>(
          this,
          Invocation.method(
            #getOrganization,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.GetOrganizationResponse>);
  @override
  _i4.ResponseFuture<_i11.GetOrganizationNamespaceAvailabilityResponse>
      getOrganizationNamespaceAvailability(
    _i11.GetOrganizationNamespaceAvailabilityRequest? request, {
    _i3.CallOptions? options,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getOrganizationNamespaceAvailability,
              [request],
              {#options: options},
            ),
            returnValue: _FakeResponseFuture_2<
                _i11.GetOrganizationNamespaceAvailabilityResponse>(
              this,
              Invocation.method(
                #getOrganizationNamespaceAvailability,
                [request],
                {#options: options},
              ),
            ),
            returnValueForMissingStub: _FakeResponseFuture_2<
                _i11.GetOrganizationNamespaceAvailabilityResponse>(
              this,
              Invocation.method(
                #getOrganizationNamespaceAvailability,
                [request],
                {#options: options},
              ),
            ),
          ) as _i4.ResponseFuture<
              _i11.GetOrganizationNamespaceAvailabilityResponse>);
  @override
  _i4.ResponseFuture<_i11.UpdateOrganizationResponse> updateOrganization(
    _i11.UpdateOrganizationRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOrganization,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.UpdateOrganizationResponse>(
          this,
          Invocation.method(
            #updateOrganization,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.UpdateOrganizationResponse>(
          this,
          Invocation.method(
            #updateOrganization,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.UpdateOrganizationResponse>);
  @override
  _i4.ResponseFuture<_i11.DeleteOrganizationResponse> deleteOrganization(
    _i11.DeleteOrganizationRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteOrganization,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.DeleteOrganizationResponse>(
          this,
          Invocation.method(
            #deleteOrganization,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.DeleteOrganizationResponse>(
          this,
          Invocation.method(
            #deleteOrganization,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.DeleteOrganizationResponse>);
  @override
  _i4.ResponseFuture<_i11.ListOrganizationMembersResponse>
      listOrganizationMembers(
    _i11.ListOrganizationMembersRequest? request, {
    _i3.CallOptions? options,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #listOrganizationMembers,
              [request],
              {#options: options},
            ),
            returnValue:
                _FakeResponseFuture_2<_i11.ListOrganizationMembersResponse>(
              this,
              Invocation.method(
                #listOrganizationMembers,
                [request],
                {#options: options},
              ),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_2<_i11.ListOrganizationMembersResponse>(
              this,
              Invocation.method(
                #listOrganizationMembers,
                [request],
                {#options: options},
              ),
            ),
          ) as _i4.ResponseFuture<_i11.ListOrganizationMembersResponse>);
  @override
  _i4.ResponseFuture<_i11.CreateOrganizationInviteResponse>
      createOrganizationInvite(
    _i11.CreateOrganizationInviteRequest? request, {
    _i3.CallOptions? options,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #createOrganizationInvite,
              [request],
              {#options: options},
            ),
            returnValue:
                _FakeResponseFuture_2<_i11.CreateOrganizationInviteResponse>(
              this,
              Invocation.method(
                #createOrganizationInvite,
                [request],
                {#options: options},
              ),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_2<_i11.CreateOrganizationInviteResponse>(
              this,
              Invocation.method(
                #createOrganizationInvite,
                [request],
                {#options: options},
              ),
            ),
          ) as _i4.ResponseFuture<_i11.CreateOrganizationInviteResponse>);
  @override
  _i4.ResponseFuture<_i11.UpdateOrganizationInviteAuthorizationsResponse>
      updateOrganizationInviteAuthorizations(
    _i11.UpdateOrganizationInviteAuthorizationsRequest? request, {
    _i3.CallOptions? options,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #updateOrganizationInviteAuthorizations,
              [request],
              {#options: options},
            ),
            returnValue: _FakeResponseFuture_2<
                _i11.UpdateOrganizationInviteAuthorizationsResponse>(
              this,
              Invocation.method(
                #updateOrganizationInviteAuthorizations,
                [request],
                {#options: options},
              ),
            ),
            returnValueForMissingStub: _FakeResponseFuture_2<
                _i11.UpdateOrganizationInviteAuthorizationsResponse>(
              this,
              Invocation.method(
                #updateOrganizationInviteAuthorizations,
                [request],
                {#options: options},
              ),
            ),
          ) as _i4.ResponseFuture<
              _i11.UpdateOrganizationInviteAuthorizationsResponse>);
  @override
  _i4.ResponseFuture<_i11.DeleteOrganizationMemberResponse>
      deleteOrganizationMember(
    _i11.DeleteOrganizationMemberRequest? request, {
    _i3.CallOptions? options,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #deleteOrganizationMember,
              [request],
              {#options: options},
            ),
            returnValue:
                _FakeResponseFuture_2<_i11.DeleteOrganizationMemberResponse>(
              this,
              Invocation.method(
                #deleteOrganizationMember,
                [request],
                {#options: options},
              ),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_2<_i11.DeleteOrganizationMemberResponse>(
              this,
              Invocation.method(
                #deleteOrganizationMember,
                [request],
                {#options: options},
              ),
            ),
          ) as _i4.ResponseFuture<_i11.DeleteOrganizationMemberResponse>);
  @override
  _i4.ResponseFuture<_i11.DeleteOrganizationInviteResponse>
      deleteOrganizationInvite(
    _i11.DeleteOrganizationInviteRequest? request, {
    _i3.CallOptions? options,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #deleteOrganizationInvite,
              [request],
              {#options: options},
            ),
            returnValue:
                _FakeResponseFuture_2<_i11.DeleteOrganizationInviteResponse>(
              this,
              Invocation.method(
                #deleteOrganizationInvite,
                [request],
                {#options: options},
              ),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_2<_i11.DeleteOrganizationInviteResponse>(
              this,
              Invocation.method(
                #deleteOrganizationInvite,
                [request],
                {#options: options},
              ),
            ),
          ) as _i4.ResponseFuture<_i11.DeleteOrganizationInviteResponse>);
  @override
  _i4.ResponseFuture<_i11.ResendOrganizationInviteResponse>
      resendOrganizationInvite(
    _i11.ResendOrganizationInviteRequest? request, {
    _i3.CallOptions? options,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #resendOrganizationInvite,
              [request],
              {#options: options},
            ),
            returnValue:
                _FakeResponseFuture_2<_i11.ResendOrganizationInviteResponse>(
              this,
              Invocation.method(
                #resendOrganizationInvite,
                [request],
                {#options: options},
              ),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_2<_i11.ResendOrganizationInviteResponse>(
              this,
              Invocation.method(
                #resendOrganizationInvite,
                [request],
                {#options: options},
              ),
            ),
          ) as _i4.ResponseFuture<_i11.ResendOrganizationInviteResponse>);
  @override
  _i4.ResponseFuture<_i11.CreateLocationResponse> createLocation(
    _i11.CreateLocationRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createLocation,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.CreateLocationResponse>(
          this,
          Invocation.method(
            #createLocation,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.CreateLocationResponse>(
          this,
          Invocation.method(
            #createLocation,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.CreateLocationResponse>);
  @override
  _i4.ResponseFuture<_i11.GetLocationResponse> getLocation(
    _i11.GetLocationRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocation,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.GetLocationResponse>(
          this,
          Invocation.method(
            #getLocation,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.GetLocationResponse>(
          this,
          Invocation.method(
            #getLocation,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.GetLocationResponse>);
  @override
  _i4.ResponseFuture<_i11.UpdateLocationResponse> updateLocation(
    _i11.UpdateLocationRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLocation,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.UpdateLocationResponse>(
          this,
          Invocation.method(
            #updateLocation,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.UpdateLocationResponse>(
          this,
          Invocation.method(
            #updateLocation,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.UpdateLocationResponse>);
  @override
  _i4.ResponseFuture<_i11.DeleteLocationResponse> deleteLocation(
    _i11.DeleteLocationRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteLocation,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.DeleteLocationResponse>(
          this,
          Invocation.method(
            #deleteLocation,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.DeleteLocationResponse>(
          this,
          Invocation.method(
            #deleteLocation,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.DeleteLocationResponse>);
  @override
  _i4.ResponseFuture<_i11.ListLocationsResponse> listLocations(
    _i11.ListLocationsRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listLocations,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.ListLocationsResponse>(
          this,
          Invocation.method(
            #listLocations,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.ListLocationsResponse>(
          this,
          Invocation.method(
            #listLocations,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.ListLocationsResponse>);
  @override
  _i4.ResponseFuture<_i11.ShareLocationResponse> shareLocation(
    _i11.ShareLocationRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #shareLocation,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.ShareLocationResponse>(
          this,
          Invocation.method(
            #shareLocation,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.ShareLocationResponse>(
          this,
          Invocation.method(
            #shareLocation,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.ShareLocationResponse>);
  @override
  _i4.ResponseFuture<_i11.UnshareLocationResponse> unshareLocation(
    _i11.UnshareLocationRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #unshareLocation,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.UnshareLocationResponse>(
          this,
          Invocation.method(
            #unshareLocation,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.UnshareLocationResponse>(
          this,
          Invocation.method(
            #unshareLocation,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.UnshareLocationResponse>);
  @override
  _i4.ResponseFuture<_i11.LocationAuthResponse> locationAuth(
    _i11.LocationAuthRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #locationAuth,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.LocationAuthResponse>(
          this,
          Invocation.method(
            #locationAuth,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.LocationAuthResponse>(
          this,
          Invocation.method(
            #locationAuth,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.LocationAuthResponse>);
  @override
  _i4.ResponseFuture<_i11.CreateLocationSecretResponse> createLocationSecret(
    _i11.CreateLocationSecretRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createLocationSecret,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.CreateLocationSecretResponse>(
          this,
          Invocation.method(
            #createLocationSecret,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.CreateLocationSecretResponse>(
          this,
          Invocation.method(
            #createLocationSecret,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.CreateLocationSecretResponse>);
  @override
  _i4.ResponseFuture<_i11.DeleteLocationSecretResponse> deleteLocationSecret(
    _i11.DeleteLocationSecretRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteLocationSecret,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.DeleteLocationSecretResponse>(
          this,
          Invocation.method(
            #deleteLocationSecret,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.DeleteLocationSecretResponse>(
          this,
          Invocation.method(
            #deleteLocationSecret,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.DeleteLocationSecretResponse>);
  @override
  _i4.ResponseFuture<_i11.GetRobotResponse> getRobot(
    _i11.GetRobotRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRobot,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.GetRobotResponse>(
          this,
          Invocation.method(
            #getRobot,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i11.GetRobotResponse>(
          this,
          Invocation.method(
            #getRobot,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.GetRobotResponse>);
  @override
  _i4.ResponseFuture<_i11.GetRoverRentalRobotsResponse> getRoverRentalRobots(
    _i11.GetRoverRentalRobotsRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRoverRentalRobots,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.GetRoverRentalRobotsResponse>(
          this,
          Invocation.method(
            #getRoverRentalRobots,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.GetRoverRentalRobotsResponse>(
          this,
          Invocation.method(
            #getRoverRentalRobots,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.GetRoverRentalRobotsResponse>);
  @override
  _i4.ResponseFuture<_i11.GetRobotPartsResponse> getRobotParts(
    _i11.GetRobotPartsRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRobotParts,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.GetRobotPartsResponse>(
          this,
          Invocation.method(
            #getRobotParts,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.GetRobotPartsResponse>(
          this,
          Invocation.method(
            #getRobotParts,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.GetRobotPartsResponse>);
  @override
  _i4.ResponseFuture<_i11.GetRobotPartResponse> getRobotPart(
    _i11.GetRobotPartRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRobotPart,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.GetRobotPartResponse>(
          this,
          Invocation.method(
            #getRobotPart,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.GetRobotPartResponse>(
          this,
          Invocation.method(
            #getRobotPart,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.GetRobotPartResponse>);
  @override
  _i4.ResponseFuture<_i11.GetRobotPartLogsResponse> getRobotPartLogs(
    _i11.GetRobotPartLogsRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRobotPartLogs,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.GetRobotPartLogsResponse>(
          this,
          Invocation.method(
            #getRobotPartLogs,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.GetRobotPartLogsResponse>(
          this,
          Invocation.method(
            #getRobotPartLogs,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.GetRobotPartLogsResponse>);
  @override
  _i4.ResponseStream<_i11.TailRobotPartLogsResponse> tailRobotPartLogs(
    _i11.TailRobotPartLogsRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #tailRobotPartLogs,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseStream_3<_i11.TailRobotPartLogsResponse>(
          this,
          Invocation.method(
            #tailRobotPartLogs,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseStream_3<_i11.TailRobotPartLogsResponse>(
          this,
          Invocation.method(
            #tailRobotPartLogs,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseStream<_i11.TailRobotPartLogsResponse>);
  @override
  _i4.ResponseFuture<_i11.GetRobotPartHistoryResponse> getRobotPartHistory(
    _i11.GetRobotPartHistoryRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRobotPartHistory,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.GetRobotPartHistoryResponse>(
          this,
          Invocation.method(
            #getRobotPartHistory,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.GetRobotPartHistoryResponse>(
          this,
          Invocation.method(
            #getRobotPartHistory,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.GetRobotPartHistoryResponse>);
  @override
  _i4.ResponseFuture<_i11.UpdateRobotPartResponse> updateRobotPart(
    _i11.UpdateRobotPartRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRobotPart,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.UpdateRobotPartResponse>(
          this,
          Invocation.method(
            #updateRobotPart,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.UpdateRobotPartResponse>(
          this,
          Invocation.method(
            #updateRobotPart,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.UpdateRobotPartResponse>);
  @override
  _i4.ResponseFuture<_i11.NewRobotPartResponse> newRobotPart(
    _i11.NewRobotPartRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #newRobotPart,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.NewRobotPartResponse>(
          this,
          Invocation.method(
            #newRobotPart,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.NewRobotPartResponse>(
          this,
          Invocation.method(
            #newRobotPart,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.NewRobotPartResponse>);
  @override
  _i4.ResponseFuture<_i11.DeleteRobotPartResponse> deleteRobotPart(
    _i11.DeleteRobotPartRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRobotPart,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.DeleteRobotPartResponse>(
          this,
          Invocation.method(
            #deleteRobotPart,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.DeleteRobotPartResponse>(
          this,
          Invocation.method(
            #deleteRobotPart,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.DeleteRobotPartResponse>);
  @override
  _i4.ResponseFuture<_i11.MarkPartAsMainResponse> markPartAsMain(
    _i11.MarkPartAsMainRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #markPartAsMain,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.MarkPartAsMainResponse>(
          this,
          Invocation.method(
            #markPartAsMain,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.MarkPartAsMainResponse>(
          this,
          Invocation.method(
            #markPartAsMain,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.MarkPartAsMainResponse>);
  @override
  _i4.ResponseFuture<_i11.MarkPartForRestartResponse> markPartForRestart(
    _i11.MarkPartForRestartRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #markPartForRestart,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.MarkPartForRestartResponse>(
          this,
          Invocation.method(
            #markPartForRestart,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.MarkPartForRestartResponse>(
          this,
          Invocation.method(
            #markPartForRestart,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.MarkPartForRestartResponse>);
  @override
  _i4.ResponseFuture<_i11.CreateRobotPartSecretResponse> createRobotPartSecret(
    _i11.CreateRobotPartSecretRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createRobotPartSecret,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.CreateRobotPartSecretResponse>(
          this,
          Invocation.method(
            #createRobotPartSecret,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.CreateRobotPartSecretResponse>(
          this,
          Invocation.method(
            #createRobotPartSecret,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.CreateRobotPartSecretResponse>);
  @override
  _i4.ResponseFuture<_i11.DeleteRobotPartSecretResponse> deleteRobotPartSecret(
    _i11.DeleteRobotPartSecretRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRobotPartSecret,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.DeleteRobotPartSecretResponse>(
          this,
          Invocation.method(
            #deleteRobotPartSecret,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.DeleteRobotPartSecretResponse>(
          this,
          Invocation.method(
            #deleteRobotPartSecret,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.DeleteRobotPartSecretResponse>);
  @override
  _i4.ResponseFuture<_i11.ListRobotsResponse> listRobots(
    _i11.ListRobotsRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listRobots,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.ListRobotsResponse>(
          this,
          Invocation.method(
            #listRobots,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.ListRobotsResponse>(
          this,
          Invocation.method(
            #listRobots,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.ListRobotsResponse>);
  @override
  _i4.ResponseFuture<_i11.NewRobotResponse> newRobot(
    _i11.NewRobotRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #newRobot,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.NewRobotResponse>(
          this,
          Invocation.method(
            #newRobot,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i11.NewRobotResponse>(
          this,
          Invocation.method(
            #newRobot,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.NewRobotResponse>);
  @override
  _i4.ResponseFuture<_i11.UpdateRobotResponse> updateRobot(
    _i11.UpdateRobotRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRobot,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.UpdateRobotResponse>(
          this,
          Invocation.method(
            #updateRobot,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.UpdateRobotResponse>(
          this,
          Invocation.method(
            #updateRobot,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.UpdateRobotResponse>);
  @override
  _i4.ResponseFuture<_i11.DeleteRobotResponse> deleteRobot(
    _i11.DeleteRobotRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRobot,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.DeleteRobotResponse>(
          this,
          Invocation.method(
            #deleteRobot,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.DeleteRobotResponse>(
          this,
          Invocation.method(
            #deleteRobot,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.DeleteRobotResponse>);
  @override
  _i4.ResponseFuture<_i11.ListFragmentsResponse> listFragments(
    _i11.ListFragmentsRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listFragments,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.ListFragmentsResponse>(
          this,
          Invocation.method(
            #listFragments,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.ListFragmentsResponse>(
          this,
          Invocation.method(
            #listFragments,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.ListFragmentsResponse>);
  @override
  _i4.ResponseFuture<_i11.GetFragmentResponse> getFragment(
    _i11.GetFragmentRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFragment,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.GetFragmentResponse>(
          this,
          Invocation.method(
            #getFragment,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.GetFragmentResponse>(
          this,
          Invocation.method(
            #getFragment,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.GetFragmentResponse>);
  @override
  _i4.ResponseFuture<_i11.CreateFragmentResponse> createFragment(
    _i11.CreateFragmentRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFragment,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.CreateFragmentResponse>(
          this,
          Invocation.method(
            #createFragment,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.CreateFragmentResponse>(
          this,
          Invocation.method(
            #createFragment,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.CreateFragmentResponse>);
  @override
  _i4.ResponseFuture<_i11.UpdateFragmentResponse> updateFragment(
    _i11.UpdateFragmentRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFragment,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.UpdateFragmentResponse>(
          this,
          Invocation.method(
            #updateFragment,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.UpdateFragmentResponse>(
          this,
          Invocation.method(
            #updateFragment,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.UpdateFragmentResponse>);
  @override
  _i4.ResponseFuture<_i11.DeleteFragmentResponse> deleteFragment(
    _i11.DeleteFragmentRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFragment,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.DeleteFragmentResponse>(
          this,
          Invocation.method(
            #deleteFragment,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.DeleteFragmentResponse>(
          this,
          Invocation.method(
            #deleteFragment,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.DeleteFragmentResponse>);
  @override
  _i4.ResponseFuture<_i11.AddRoleResponse> addRole(
    _i11.AddRoleRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRole,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.AddRoleResponse>(
          this,
          Invocation.method(
            #addRole,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i11.AddRoleResponse>(
          this,
          Invocation.method(
            #addRole,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.AddRoleResponse>);
  @override
  _i4.ResponseFuture<_i11.RemoveRoleResponse> removeRole(
    _i11.RemoveRoleRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeRole,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.RemoveRoleResponse>(
          this,
          Invocation.method(
            #removeRole,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.RemoveRoleResponse>(
          this,
          Invocation.method(
            #removeRole,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.RemoveRoleResponse>);
  @override
  _i4.ResponseFuture<_i11.ListAuthorizationsResponse> listAuthorizations(
    _i11.ListAuthorizationsRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listAuthorizations,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.ListAuthorizationsResponse>(
          this,
          Invocation.method(
            #listAuthorizations,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.ListAuthorizationsResponse>(
          this,
          Invocation.method(
            #listAuthorizations,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.ListAuthorizationsResponse>);
  @override
  _i4.ResponseFuture<_i11.CheckPermissionsResponse> checkPermissions(
    _i11.CheckPermissionsRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkPermissions,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.CheckPermissionsResponse>(
          this,
          Invocation.method(
            #checkPermissions,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.CheckPermissionsResponse>(
          this,
          Invocation.method(
            #checkPermissions,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.CheckPermissionsResponse>);
  @override
  _i4.ResponseFuture<_i11.CreateModuleResponse> createModule(
    _i11.CreateModuleRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createModule,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.CreateModuleResponse>(
          this,
          Invocation.method(
            #createModule,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.CreateModuleResponse>(
          this,
          Invocation.method(
            #createModule,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.CreateModuleResponse>);
  @override
  _i4.ResponseFuture<_i11.UpdateModuleResponse> updateModule(
    _i11.UpdateModuleRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateModule,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.UpdateModuleResponse>(
          this,
          Invocation.method(
            #updateModule,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.UpdateModuleResponse>(
          this,
          Invocation.method(
            #updateModule,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.UpdateModuleResponse>);
  @override
  _i4.ResponseFuture<_i11.UploadModuleFileResponse> uploadModuleFile(
    _i6.Stream<_i11.UploadModuleFileRequest>? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadModuleFile,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.UploadModuleFileResponse>(
          this,
          Invocation.method(
            #uploadModuleFile,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.UploadModuleFileResponse>(
          this,
          Invocation.method(
            #uploadModuleFile,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.UploadModuleFileResponse>);
  @override
  _i4.ResponseFuture<_i11.GetModuleResponse> getModule(
    _i11.GetModuleRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getModule,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.GetModuleResponse>(
          this,
          Invocation.method(
            #getModule,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.GetModuleResponse>(
          this,
          Invocation.method(
            #getModule,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.GetModuleResponse>);
  @override
  _i4.ResponseFuture<_i11.ListModulesResponse> listModules(
    _i11.ListModulesRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listModules,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.ListModulesResponse>(
          this,
          Invocation.method(
            #listModules,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i11.ListModulesResponse>(
          this,
          Invocation.method(
            #listModules,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.ListModulesResponse>);
  @override
  _i3.ClientCall<Q, R> $createCall<Q, R>(
    _i7.ClientMethod<Q, R>? method,
    _i6.Stream<Q>? requests, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createCall,
          [
            method,
            requests,
          ],
          {#options: options},
        ),
        returnValue: _FakeClientCall_1<Q, R>(
          this,
          Invocation.method(
            #$createCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeClientCall_1<Q, R>(
          this,
          Invocation.method(
            #$createCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
      ) as _i3.ClientCall<Q, R>);
  @override
  _i4.ResponseFuture<R> $createUnaryCall<Q, R>(
    _i7.ClientMethod<Q, R>? method,
    Q? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createUnaryCall,
          [
            method,
            request,
          ],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<R>(
          this,
          Invocation.method(
            #$createUnaryCall,
            [
              method,
              request,
            ],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<R>(
          this,
          Invocation.method(
            #$createUnaryCall,
            [
              method,
              request,
            ],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<R>);
  @override
  _i4.ResponseStream<R> $createStreamingCall<Q, R>(
    _i7.ClientMethod<Q, R>? method,
    _i6.Stream<Q>? requests, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createStreamingCall,
          [
            method,
            requests,
          ],
          {#options: options},
        ),
        returnValue: _FakeResponseStream_3<R>(
          this,
          Invocation.method(
            #$createStreamingCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseStream_3<R>(
          this,
          Invocation.method(
            #$createStreamingCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseStream<R>);
}

/// A class which mocks [DataServiceClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockDataServiceClient extends _i1.Mock implements _i12.DataServiceClient {
  @override
  _i4.ResponseFuture<_i13.TabularDataByFilterResponse> tabularDataByFilter(
    _i13.TabularDataByFilterRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #tabularDataByFilter,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.TabularDataByFilterResponse>(
          this,
          Invocation.method(
            #tabularDataByFilter,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i13.TabularDataByFilterResponse>(
          this,
          Invocation.method(
            #tabularDataByFilter,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.TabularDataByFilterResponse>);
  @override
  _i4.ResponseFuture<_i13.BinaryDataByFilterResponse> binaryDataByFilter(
    _i13.BinaryDataByFilterRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #binaryDataByFilter,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.BinaryDataByFilterResponse>(
          this,
          Invocation.method(
            #binaryDataByFilter,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i13.BinaryDataByFilterResponse>(
          this,
          Invocation.method(
            #binaryDataByFilter,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.BinaryDataByFilterResponse>);
  @override
  _i4.ResponseFuture<_i13.BinaryDataByIDsResponse> binaryDataByIDs(
    _i13.BinaryDataByIDsRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #binaryDataByIDs,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.BinaryDataByIDsResponse>(
          this,
          Invocation.method(
            #binaryDataByIDs,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i13.BinaryDataByIDsResponse>(
          this,
          Invocation.method(
            #binaryDataByIDs,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.BinaryDataByIDsResponse>);
  @override
  _i4.ResponseFuture<_i13.DeleteTabularDataByFilterResponse>
      deleteTabularDataByFilter(
    _i13.DeleteTabularDataByFilterRequest? request, {
    _i3.CallOptions? options,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #deleteTabularDataByFilter,
              [request],
              {#options: options},
            ),
            returnValue:
                _FakeResponseFuture_2<_i13.DeleteTabularDataByFilterResponse>(
              this,
              Invocation.method(
                #deleteTabularDataByFilter,
                [request],
                {#options: options},
              ),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_2<_i13.DeleteTabularDataByFilterResponse>(
              this,
              Invocation.method(
                #deleteTabularDataByFilter,
                [request],
                {#options: options},
              ),
            ),
          ) as _i4.ResponseFuture<_i13.DeleteTabularDataByFilterResponse>);
  @override
  _i4.ResponseFuture<_i13.DeleteBinaryDataByFilterResponse>
      deleteBinaryDataByFilter(
    _i13.DeleteBinaryDataByFilterRequest? request, {
    _i3.CallOptions? options,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #deleteBinaryDataByFilter,
              [request],
              {#options: options},
            ),
            returnValue:
                _FakeResponseFuture_2<_i13.DeleteBinaryDataByFilterResponse>(
              this,
              Invocation.method(
                #deleteBinaryDataByFilter,
                [request],
                {#options: options},
              ),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_2<_i13.DeleteBinaryDataByFilterResponse>(
              this,
              Invocation.method(
                #deleteBinaryDataByFilter,
                [request],
                {#options: options},
              ),
            ),
          ) as _i4.ResponseFuture<_i13.DeleteBinaryDataByFilterResponse>);
  @override
  _i4.ResponseFuture<_i13.DeleteBinaryDataByIDsResponse> deleteBinaryDataByIDs(
    _i13.DeleteBinaryDataByIDsRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteBinaryDataByIDs,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.DeleteBinaryDataByIDsResponse>(
          this,
          Invocation.method(
            #deleteBinaryDataByIDs,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i13.DeleteBinaryDataByIDsResponse>(
          this,
          Invocation.method(
            #deleteBinaryDataByIDs,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.DeleteBinaryDataByIDsResponse>);
  @override
  _i4.ResponseFuture<_i13.AddTagsToBinaryDataByIDsResponse>
      addTagsToBinaryDataByIDs(
    _i13.AddTagsToBinaryDataByIDsRequest? request, {
    _i3.CallOptions? options,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #addTagsToBinaryDataByIDs,
              [request],
              {#options: options},
            ),
            returnValue:
                _FakeResponseFuture_2<_i13.AddTagsToBinaryDataByIDsResponse>(
              this,
              Invocation.method(
                #addTagsToBinaryDataByIDs,
                [request],
                {#options: options},
              ),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_2<_i13.AddTagsToBinaryDataByIDsResponse>(
              this,
              Invocation.method(
                #addTagsToBinaryDataByIDs,
                [request],
                {#options: options},
              ),
            ),
          ) as _i4.ResponseFuture<_i13.AddTagsToBinaryDataByIDsResponse>);
  @override
  _i4.ResponseFuture<_i13.AddTagsToBinaryDataByFilterResponse>
      addTagsToBinaryDataByFilter(
    _i13.AddTagsToBinaryDataByFilterRequest? request, {
    _i3.CallOptions? options,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #addTagsToBinaryDataByFilter,
              [request],
              {#options: options},
            ),
            returnValue:
                _FakeResponseFuture_2<_i13.AddTagsToBinaryDataByFilterResponse>(
              this,
              Invocation.method(
                #addTagsToBinaryDataByFilter,
                [request],
                {#options: options},
              ),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_2<_i13.AddTagsToBinaryDataByFilterResponse>(
              this,
              Invocation.method(
                #addTagsToBinaryDataByFilter,
                [request],
                {#options: options},
              ),
            ),
          ) as _i4.ResponseFuture<_i13.AddTagsToBinaryDataByFilterResponse>);
  @override
  _i4.ResponseFuture<
      _i13.RemoveTagsFromBinaryDataByIDsResponse> removeTagsFromBinaryDataByIDs(
    _i13.RemoveTagsFromBinaryDataByIDsRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeTagsFromBinaryDataByIDs,
          [request],
          {#options: options},
        ),
        returnValue:
            _FakeResponseFuture_2<_i13.RemoveTagsFromBinaryDataByIDsResponse>(
          this,
          Invocation.method(
            #removeTagsFromBinaryDataByIDs,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i13.RemoveTagsFromBinaryDataByIDsResponse>(
          this,
          Invocation.method(
            #removeTagsFromBinaryDataByIDs,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.RemoveTagsFromBinaryDataByIDsResponse>);
  @override
  _i4.ResponseFuture<_i13.RemoveTagsFromBinaryDataByFilterResponse>
      removeTagsFromBinaryDataByFilter(
    _i13.RemoveTagsFromBinaryDataByFilterRequest? request, {
    _i3.CallOptions? options,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #removeTagsFromBinaryDataByFilter,
              [request],
              {#options: options},
            ),
            returnValue: _FakeResponseFuture_2<
                _i13.RemoveTagsFromBinaryDataByFilterResponse>(
              this,
              Invocation.method(
                #removeTagsFromBinaryDataByFilter,
                [request],
                {#options: options},
              ),
            ),
            returnValueForMissingStub: _FakeResponseFuture_2<
                _i13.RemoveTagsFromBinaryDataByFilterResponse>(
              this,
              Invocation.method(
                #removeTagsFromBinaryDataByFilter,
                [request],
                {#options: options},
              ),
            ),
          ) as _i4
              .ResponseFuture<_i13.RemoveTagsFromBinaryDataByFilterResponse>);
  @override
  _i4.ResponseFuture<_i13.TagsByFilterResponse> tagsByFilter(
    _i13.TagsByFilterRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #tagsByFilter,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.TagsByFilterResponse>(
          this,
          Invocation.method(
            #tagsByFilter,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i13.TagsByFilterResponse>(
          this,
          Invocation.method(
            #tagsByFilter,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.TagsByFilterResponse>);
  @override
  _i4.ResponseFuture<_i13.AddBoundingBoxToImageByIDResponse>
      addBoundingBoxToImageByID(
    _i13.AddBoundingBoxToImageByIDRequest? request, {
    _i3.CallOptions? options,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #addBoundingBoxToImageByID,
              [request],
              {#options: options},
            ),
            returnValue:
                _FakeResponseFuture_2<_i13.AddBoundingBoxToImageByIDResponse>(
              this,
              Invocation.method(
                #addBoundingBoxToImageByID,
                [request],
                {#options: options},
              ),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_2<_i13.AddBoundingBoxToImageByIDResponse>(
              this,
              Invocation.method(
                #addBoundingBoxToImageByID,
                [request],
                {#options: options},
              ),
            ),
          ) as _i4.ResponseFuture<_i13.AddBoundingBoxToImageByIDResponse>);
  @override
  _i4.ResponseFuture<
      _i13
      .RemoveBoundingBoxFromImageByIDResponse> removeBoundingBoxFromImageByID(
    _i13.RemoveBoundingBoxFromImageByIDRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeBoundingBoxFromImageByID,
          [request],
          {#options: options},
        ),
        returnValue:
            _FakeResponseFuture_2<_i13.RemoveBoundingBoxFromImageByIDResponse>(
          this,
          Invocation.method(
            #removeBoundingBoxFromImageByID,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub:
            _FakeResponseFuture_2<_i13.RemoveBoundingBoxFromImageByIDResponse>(
          this,
          Invocation.method(
            #removeBoundingBoxFromImageByID,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.RemoveBoundingBoxFromImageByIDResponse>);
  @override
  _i4.ResponseFuture<_i13.BoundingBoxLabelsByFilterResponse>
      boundingBoxLabelsByFilter(
    _i13.BoundingBoxLabelsByFilterRequest? request, {
    _i3.CallOptions? options,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #boundingBoxLabelsByFilter,
              [request],
              {#options: options},
            ),
            returnValue:
                _FakeResponseFuture_2<_i13.BoundingBoxLabelsByFilterResponse>(
              this,
              Invocation.method(
                #boundingBoxLabelsByFilter,
                [request],
                {#options: options},
              ),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_2<_i13.BoundingBoxLabelsByFilterResponse>(
              this,
              Invocation.method(
                #boundingBoxLabelsByFilter,
                [request],
                {#options: options},
              ),
            ),
          ) as _i4.ResponseFuture<_i13.BoundingBoxLabelsByFilterResponse>);
  @override
  _i3.ClientCall<Q, R> $createCall<Q, R>(
    _i7.ClientMethod<Q, R>? method,
    _i6.Stream<Q>? requests, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createCall,
          [
            method,
            requests,
          ],
          {#options: options},
        ),
        returnValue: _FakeClientCall_1<Q, R>(
          this,
          Invocation.method(
            #$createCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeClientCall_1<Q, R>(
          this,
          Invocation.method(
            #$createCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
      ) as _i3.ClientCall<Q, R>);
  @override
  _i4.ResponseFuture<R> $createUnaryCall<Q, R>(
    _i7.ClientMethod<Q, R>? method,
    Q? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createUnaryCall,
          [
            method,
            request,
          ],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<R>(
          this,
          Invocation.method(
            #$createUnaryCall,
            [
              method,
              request,
            ],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<R>(
          this,
          Invocation.method(
            #$createUnaryCall,
            [
              method,
              request,
            ],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<R>);
  @override
  _i4.ResponseStream<R> $createStreamingCall<Q, R>(
    _i7.ClientMethod<Q, R>? method,
    _i6.Stream<Q>? requests, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createStreamingCall,
          [
            method,
            requests,
          ],
          {#options: options},
        ),
        returnValue: _FakeResponseStream_3<R>(
          this,
          Invocation.method(
            #$createStreamingCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseStream_3<R>(
          this,
          Invocation.method(
            #$createStreamingCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseStream<R>);
}
