// Mocks generated by Mockito 5.4.2 from annotations
// in viam_sdk/test/unit_test/mocks/service_clients_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:grpc/service_api.dart' as _i4;
import 'package:grpc/src/client/call.dart' as _i3;
import 'package:grpc/src/client/channel.dart' as _i5;
import 'package:grpc/src/client/connection.dart' as _i2;
import 'package:grpc/src/client/method.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:viam_sdk/src/components/power_sensor/client.dart' as _i16;
import 'package:viam_sdk/src/components/power_sensor/power_sensor.dart' as _i7;
import 'package:viam_sdk/src/gen/app/data/v1/data.pb.dart' as _i15;
import 'package:viam_sdk/src/gen/app/data/v1/data.pbgrpc.dart' as _i14;
import 'package:viam_sdk/src/gen/app/v1/app.pb.dart' as _i13;
import 'package:viam_sdk/src/gen/app/v1/app.pbgrpc.dart' as _i12;
import 'package:viam_sdk/src/gen/component/powersensor/v1/powersensor.pbgrpc.dart' as _i6;
import 'package:viam_sdk/src/gen/robot/v1/robot.pb.dart' as _i11;
import 'package:viam_sdk/src/gen/robot/v1/robot.pbgrpc.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClientConnection_0 extends _i1.SmartFake implements _i2.ClientConnection {
  _FakeClientConnection_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClientCall_1<Q1, R1> extends _i1.SmartFake implements _i3.ClientCall<Q1, R1> {
  _FakeClientCall_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponseFuture_2<R> extends _i1.SmartFake implements _i4.ResponseFuture<R> {
  _FakeResponseFuture_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponseStream_3<R> extends _i1.SmartFake implements _i4.ResponseStream<R> {
  _FakeResponseStream_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClientChannelBase_4 extends _i1.SmartFake implements _i5.ClientChannelBase {
  _FakeClientChannelBase_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePowerSensorServiceClient_5 extends _i1.SmartFake implements _i6.PowerSensorServiceClient {
  _FakePowerSensorServiceClient_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVoltage_6 extends _i1.SmartFake implements _i7.Voltage {
  _FakeVoltage_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCurrent_7 extends _i1.SmartFake implements _i7.Current {
  _FakeCurrent_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ClientChannelBase].
///
/// See the documentation for Mockito's code generation for more information.
class MockClientChannelBase extends _i1.Mock implements _i5.ClientChannelBase {
  @override
  _i8.Stream<_i2.ConnectionState> get onConnectionStateChanged => (super.noSuchMethod(
        Invocation.getter(#onConnectionStateChanged),
        returnValue: _i8.Stream<_i2.ConnectionState>.empty(),
        returnValueForMissingStub: _i8.Stream<_i2.ConnectionState>.empty(),
      ) as _i8.Stream<_i2.ConnectionState>);
  @override
  _i8.Future<void> shutdown() => (super.noSuchMethod(
        Invocation.method(
          #shutdown,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
  @override
  _i8.Future<void> terminate() => (super.noSuchMethod(
        Invocation.method(
          #terminate,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
  @override
  _i2.ClientConnection createConnection() => (super.noSuchMethod(
        Invocation.method(
          #createConnection,
          [],
        ),
        returnValue: _FakeClientConnection_0(
          this,
          Invocation.method(
            #createConnection,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeClientConnection_0(
          this,
          Invocation.method(
            #createConnection,
            [],
          ),
        ),
      ) as _i2.ClientConnection);
  @override
  _i8.Future<_i2.ClientConnection> getConnection() => (super.noSuchMethod(
        Invocation.method(
          #getConnection,
          [],
        ),
        returnValue: _i8.Future<_i2.ClientConnection>.value(_FakeClientConnection_0(
          this,
          Invocation.method(
            #getConnection,
            [],
          ),
        )),
        returnValueForMissingStub: _i8.Future<_i2.ClientConnection>.value(_FakeClientConnection_0(
          this,
          Invocation.method(
            #getConnection,
            [],
          ),
        )),
      ) as _i8.Future<_i2.ClientConnection>);
  @override
  _i3.ClientCall<Q, R> createCall<Q, R>(
    _i9.ClientMethod<Q, R>? method,
    _i8.Stream<Q>? requests,
    _i3.CallOptions? options,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCall,
          [
            method,
            requests,
            options,
          ],
        ),
        returnValue: _FakeClientCall_1<Q, R>(
          this,
          Invocation.method(
            #createCall,
            [
              method,
              requests,
              options,
            ],
          ),
        ),
        returnValueForMissingStub: _FakeClientCall_1<Q, R>(
          this,
          Invocation.method(
            #createCall,
            [
              method,
              requests,
              options,
            ],
          ),
        ),
      ) as _i3.ClientCall<Q, R>);
}

/// A class which mocks [RobotServiceClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockRobotServiceClient extends _i1.Mock implements _i10.RobotServiceClient {
  @override
  _i4.ResponseFuture<_i11.GetOperationsResponse> getOperations(
    _i11.GetOperationsRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOperations,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.GetOperationsResponse>(
          this,
          Invocation.method(
            #getOperations,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i11.GetOperationsResponse>(
          this,
          Invocation.method(
            #getOperations,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.GetOperationsResponse>);
  @override
  _i4.ResponseFuture<_i11.GetSessionsResponse> getSessions(
    _i11.GetSessionsRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSessions,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.GetSessionsResponse>(
          this,
          Invocation.method(
            #getSessions,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i11.GetSessionsResponse>(
          this,
          Invocation.method(
            #getSessions,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.GetSessionsResponse>);
  @override
  _i4.ResponseFuture<_i11.ResourceNamesResponse> resourceNames(
    _i11.ResourceNamesRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resourceNames,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.ResourceNamesResponse>(
          this,
          Invocation.method(
            #resourceNames,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i11.ResourceNamesResponse>(
          this,
          Invocation.method(
            #resourceNames,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.ResourceNamesResponse>);
  @override
  _i4.ResponseFuture<_i11.ResourceRPCSubtypesResponse> resourceRPCSubtypes(
    _i11.ResourceRPCSubtypesRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resourceRPCSubtypes,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.ResourceRPCSubtypesResponse>(
          this,
          Invocation.method(
            #resourceRPCSubtypes,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i11.ResourceRPCSubtypesResponse>(
          this,
          Invocation.method(
            #resourceRPCSubtypes,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.ResourceRPCSubtypesResponse>);
  @override
  _i4.ResponseFuture<_i11.CancelOperationResponse> cancelOperation(
    _i11.CancelOperationRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelOperation,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.CancelOperationResponse>(
          this,
          Invocation.method(
            #cancelOperation,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i11.CancelOperationResponse>(
          this,
          Invocation.method(
            #cancelOperation,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.CancelOperationResponse>);
  @override
  _i4.ResponseFuture<_i11.BlockForOperationResponse> blockForOperation(
    _i11.BlockForOperationRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #blockForOperation,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.BlockForOperationResponse>(
          this,
          Invocation.method(
            #blockForOperation,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i11.BlockForOperationResponse>(
          this,
          Invocation.method(
            #blockForOperation,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.BlockForOperationResponse>);
  @override
  _i4.ResponseFuture<_i11.DiscoverComponentsResponse> discoverComponents(
    _i11.DiscoverComponentsRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverComponents,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.DiscoverComponentsResponse>(
          this,
          Invocation.method(
            #discoverComponents,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i11.DiscoverComponentsResponse>(
          this,
          Invocation.method(
            #discoverComponents,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.DiscoverComponentsResponse>);
  @override
  _i4.ResponseFuture<_i11.FrameSystemConfigResponse> frameSystemConfig(
    _i11.FrameSystemConfigRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #frameSystemConfig,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.FrameSystemConfigResponse>(
          this,
          Invocation.method(
            #frameSystemConfig,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i11.FrameSystemConfigResponse>(
          this,
          Invocation.method(
            #frameSystemConfig,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.FrameSystemConfigResponse>);
  @override
  _i4.ResponseFuture<_i11.TransformPoseResponse> transformPose(
    _i11.TransformPoseRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transformPose,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.TransformPoseResponse>(
          this,
          Invocation.method(
            #transformPose,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i11.TransformPoseResponse>(
          this,
          Invocation.method(
            #transformPose,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.TransformPoseResponse>);
  @override
  _i4.ResponseFuture<_i11.TransformPCDResponse> transformPCD(
    _i11.TransformPCDRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transformPCD,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.TransformPCDResponse>(
          this,
          Invocation.method(
            #transformPCD,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i11.TransformPCDResponse>(
          this,
          Invocation.method(
            #transformPCD,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.TransformPCDResponse>);
  @override
  _i4.ResponseFuture<_i11.GetStatusResponse> getStatus(
    _i11.GetStatusRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStatus,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.GetStatusResponse>(
          this,
          Invocation.method(
            #getStatus,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i11.GetStatusResponse>(
          this,
          Invocation.method(
            #getStatus,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.GetStatusResponse>);
  @override
  _i4.ResponseStream<_i11.StreamStatusResponse> streamStatus(
    _i11.StreamStatusRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamStatus,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseStream_3<_i11.StreamStatusResponse>(
          this,
          Invocation.method(
            #streamStatus,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseStream_3<_i11.StreamStatusResponse>(
          this,
          Invocation.method(
            #streamStatus,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseStream<_i11.StreamStatusResponse>);
  @override
  _i4.ResponseFuture<_i11.StopAllResponse> stopAll(
    _i11.StopAllRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #stopAll,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.StopAllResponse>(
          this,
          Invocation.method(
            #stopAll,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i11.StopAllResponse>(
          this,
          Invocation.method(
            #stopAll,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.StopAllResponse>);
  @override
  _i4.ResponseFuture<_i11.StartSessionResponse> startSession(
    _i11.StartSessionRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startSession,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.StartSessionResponse>(
          this,
          Invocation.method(
            #startSession,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i11.StartSessionResponse>(
          this,
          Invocation.method(
            #startSession,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.StartSessionResponse>);
  @override
  _i4.ResponseFuture<_i11.SendSessionHeartbeatResponse> sendSessionHeartbeat(
    _i11.SendSessionHeartbeatRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendSessionHeartbeat,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i11.SendSessionHeartbeatResponse>(
          this,
          Invocation.method(
            #sendSessionHeartbeat,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i11.SendSessionHeartbeatResponse>(
          this,
          Invocation.method(
            #sendSessionHeartbeat,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i11.SendSessionHeartbeatResponse>);
  @override
  _i3.ClientCall<Q, R> $createCall<Q, R>(
    _i9.ClientMethod<Q, R>? method,
    _i8.Stream<Q>? requests, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createCall,
          [
            method,
            requests,
          ],
          {#options: options},
        ),
        returnValue: _FakeClientCall_1<Q, R>(
          this,
          Invocation.method(
            #$createCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeClientCall_1<Q, R>(
          this,
          Invocation.method(
            #$createCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
      ) as _i3.ClientCall<Q, R>);
  @override
  _i4.ResponseFuture<R> $createUnaryCall<Q, R>(
    _i9.ClientMethod<Q, R>? method,
    Q? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createUnaryCall,
          [
            method,
            request,
          ],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<R>(
          this,
          Invocation.method(
            #$createUnaryCall,
            [
              method,
              request,
            ],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<R>(
          this,
          Invocation.method(
            #$createUnaryCall,
            [
              method,
              request,
            ],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<R>);
  @override
  _i4.ResponseStream<R> $createStreamingCall<Q, R>(
    _i9.ClientMethod<Q, R>? method,
    _i8.Stream<Q>? requests, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createStreamingCall,
          [
            method,
            requests,
          ],
          {#options: options},
        ),
        returnValue: _FakeResponseStream_3<R>(
          this,
          Invocation.method(
            #$createStreamingCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseStream_3<R>(
          this,
          Invocation.method(
            #$createStreamingCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseStream<R>);
}

/// A class which mocks [AppServiceClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppServiceClient extends _i1.Mock implements _i12.AppServiceClient {
  @override
  _i4.ResponseFuture<_i13.GetUserIDByEmailResponse> getUserIDByEmail(
    _i13.GetUserIDByEmailRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserIDByEmail,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.GetUserIDByEmailResponse>(
          this,
          Invocation.method(
            #getUserIDByEmail,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.GetUserIDByEmailResponse>(
          this,
          Invocation.method(
            #getUserIDByEmail,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.GetUserIDByEmailResponse>);
  @override
  _i4.ResponseFuture<_i13.CreateOrganizationResponse> createOrganization(
    _i13.CreateOrganizationRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrganization,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.CreateOrganizationResponse>(
          this,
          Invocation.method(
            #createOrganization,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.CreateOrganizationResponse>(
          this,
          Invocation.method(
            #createOrganization,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.CreateOrganizationResponse>);
  @override
  _i4.ResponseFuture<_i13.ListOrganizationsResponse> listOrganizations(
    _i13.ListOrganizationsRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listOrganizations,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.ListOrganizationsResponse>(
          this,
          Invocation.method(
            #listOrganizations,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.ListOrganizationsResponse>(
          this,
          Invocation.method(
            #listOrganizations,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.ListOrganizationsResponse>);
  @override
  _i4.ResponseFuture<_i13.ListOrganizationsByUserResponse> listOrganizationsByUser(
    _i13.ListOrganizationsByUserRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listOrganizationsByUser,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.ListOrganizationsByUserResponse>(
          this,
          Invocation.method(
            #listOrganizationsByUser,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.ListOrganizationsByUserResponse>(
          this,
          Invocation.method(
            #listOrganizationsByUser,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.ListOrganizationsByUserResponse>);
  @override
  _i4.ResponseFuture<_i13.GetOrganizationResponse> getOrganization(
    _i13.GetOrganizationRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrganization,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.GetOrganizationResponse>(
          this,
          Invocation.method(
            #getOrganization,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.GetOrganizationResponse>(
          this,
          Invocation.method(
            #getOrganization,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.GetOrganizationResponse>);
  @override
  _i4.ResponseFuture<_i13.GetOrganizationNamespaceAvailabilityResponse> getOrganizationNamespaceAvailability(
    _i13.GetOrganizationNamespaceAvailabilityRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrganizationNamespaceAvailability,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.GetOrganizationNamespaceAvailabilityResponse>(
          this,
          Invocation.method(
            #getOrganizationNamespaceAvailability,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.GetOrganizationNamespaceAvailabilityResponse>(
          this,
          Invocation.method(
            #getOrganizationNamespaceAvailability,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.GetOrganizationNamespaceAvailabilityResponse>);
  @override
  _i4.ResponseFuture<_i13.UpdateOrganizationResponse> updateOrganization(
    _i13.UpdateOrganizationRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOrganization,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.UpdateOrganizationResponse>(
          this,
          Invocation.method(
            #updateOrganization,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.UpdateOrganizationResponse>(
          this,
          Invocation.method(
            #updateOrganization,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.UpdateOrganizationResponse>);
  @override
  _i4.ResponseFuture<_i13.DeleteOrganizationResponse> deleteOrganization(
    _i13.DeleteOrganizationRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteOrganization,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.DeleteOrganizationResponse>(
          this,
          Invocation.method(
            #deleteOrganization,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.DeleteOrganizationResponse>(
          this,
          Invocation.method(
            #deleteOrganization,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.DeleteOrganizationResponse>);
  @override
  _i4.ResponseFuture<_i13.ListOrganizationMembersResponse> listOrganizationMembers(
    _i13.ListOrganizationMembersRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listOrganizationMembers,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.ListOrganizationMembersResponse>(
          this,
          Invocation.method(
            #listOrganizationMembers,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.ListOrganizationMembersResponse>(
          this,
          Invocation.method(
            #listOrganizationMembers,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.ListOrganizationMembersResponse>);
  @override
  _i4.ResponseFuture<_i13.CreateOrganizationInviteResponse> createOrganizationInvite(
    _i13.CreateOrganizationInviteRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrganizationInvite,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.CreateOrganizationInviteResponse>(
          this,
          Invocation.method(
            #createOrganizationInvite,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.CreateOrganizationInviteResponse>(
          this,
          Invocation.method(
            #createOrganizationInvite,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.CreateOrganizationInviteResponse>);
  @override
  _i4.ResponseFuture<_i13.UpdateOrganizationInviteAuthorizationsResponse> updateOrganizationInviteAuthorizations(
    _i13.UpdateOrganizationInviteAuthorizationsRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOrganizationInviteAuthorizations,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.UpdateOrganizationInviteAuthorizationsResponse>(
          this,
          Invocation.method(
            #updateOrganizationInviteAuthorizations,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.UpdateOrganizationInviteAuthorizationsResponse>(
          this,
          Invocation.method(
            #updateOrganizationInviteAuthorizations,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.UpdateOrganizationInviteAuthorizationsResponse>);
  @override
  _i4.ResponseFuture<_i13.DeleteOrganizationMemberResponse> deleteOrganizationMember(
    _i13.DeleteOrganizationMemberRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteOrganizationMember,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.DeleteOrganizationMemberResponse>(
          this,
          Invocation.method(
            #deleteOrganizationMember,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.DeleteOrganizationMemberResponse>(
          this,
          Invocation.method(
            #deleteOrganizationMember,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.DeleteOrganizationMemberResponse>);
  @override
  _i4.ResponseFuture<_i13.DeleteOrganizationInviteResponse> deleteOrganizationInvite(
    _i13.DeleteOrganizationInviteRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteOrganizationInvite,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.DeleteOrganizationInviteResponse>(
          this,
          Invocation.method(
            #deleteOrganizationInvite,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.DeleteOrganizationInviteResponse>(
          this,
          Invocation.method(
            #deleteOrganizationInvite,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.DeleteOrganizationInviteResponse>);
  @override
  _i4.ResponseFuture<_i13.ResendOrganizationInviteResponse> resendOrganizationInvite(
    _i13.ResendOrganizationInviteRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resendOrganizationInvite,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.ResendOrganizationInviteResponse>(
          this,
          Invocation.method(
            #resendOrganizationInvite,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.ResendOrganizationInviteResponse>(
          this,
          Invocation.method(
            #resendOrganizationInvite,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.ResendOrganizationInviteResponse>);
  @override
  _i4.ResponseFuture<_i13.CreateLocationResponse> createLocation(
    _i13.CreateLocationRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createLocation,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.CreateLocationResponse>(
          this,
          Invocation.method(
            #createLocation,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.CreateLocationResponse>(
          this,
          Invocation.method(
            #createLocation,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.CreateLocationResponse>);
  @override
  _i4.ResponseFuture<_i13.GetLocationResponse> getLocation(
    _i13.GetLocationRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocation,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.GetLocationResponse>(
          this,
          Invocation.method(
            #getLocation,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.GetLocationResponse>(
          this,
          Invocation.method(
            #getLocation,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.GetLocationResponse>);
  @override
  _i4.ResponseFuture<_i13.UpdateLocationResponse> updateLocation(
    _i13.UpdateLocationRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLocation,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.UpdateLocationResponse>(
          this,
          Invocation.method(
            #updateLocation,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.UpdateLocationResponse>(
          this,
          Invocation.method(
            #updateLocation,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.UpdateLocationResponse>);
  @override
  _i4.ResponseFuture<_i13.DeleteLocationResponse> deleteLocation(
    _i13.DeleteLocationRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteLocation,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.DeleteLocationResponse>(
          this,
          Invocation.method(
            #deleteLocation,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.DeleteLocationResponse>(
          this,
          Invocation.method(
            #deleteLocation,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.DeleteLocationResponse>);
  @override
  _i4.ResponseFuture<_i13.ListLocationsResponse> listLocations(
    _i13.ListLocationsRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listLocations,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.ListLocationsResponse>(
          this,
          Invocation.method(
            #listLocations,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.ListLocationsResponse>(
          this,
          Invocation.method(
            #listLocations,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.ListLocationsResponse>);
  @override
  _i4.ResponseFuture<_i13.ShareLocationResponse> shareLocation(
    _i13.ShareLocationRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #shareLocation,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.ShareLocationResponse>(
          this,
          Invocation.method(
            #shareLocation,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.ShareLocationResponse>(
          this,
          Invocation.method(
            #shareLocation,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.ShareLocationResponse>);
  @override
  _i4.ResponseFuture<_i13.UnshareLocationResponse> unshareLocation(
    _i13.UnshareLocationRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #unshareLocation,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.UnshareLocationResponse>(
          this,
          Invocation.method(
            #unshareLocation,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.UnshareLocationResponse>(
          this,
          Invocation.method(
            #unshareLocation,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.UnshareLocationResponse>);
  @override
  _i4.ResponseFuture<_i13.LocationAuthResponse> locationAuth(
    _i13.LocationAuthRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #locationAuth,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.LocationAuthResponse>(
          this,
          Invocation.method(
            #locationAuth,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.LocationAuthResponse>(
          this,
          Invocation.method(
            #locationAuth,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.LocationAuthResponse>);
  @override
  _i4.ResponseFuture<_i13.CreateLocationSecretResponse> createLocationSecret(
    _i13.CreateLocationSecretRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createLocationSecret,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.CreateLocationSecretResponse>(
          this,
          Invocation.method(
            #createLocationSecret,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.CreateLocationSecretResponse>(
          this,
          Invocation.method(
            #createLocationSecret,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.CreateLocationSecretResponse>);
  @override
  _i4.ResponseFuture<_i13.DeleteLocationSecretResponse> deleteLocationSecret(
    _i13.DeleteLocationSecretRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteLocationSecret,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.DeleteLocationSecretResponse>(
          this,
          Invocation.method(
            #deleteLocationSecret,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.DeleteLocationSecretResponse>(
          this,
          Invocation.method(
            #deleteLocationSecret,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.DeleteLocationSecretResponse>);
  @override
  _i4.ResponseFuture<_i13.GetRobotResponse> getRobot(
    _i13.GetRobotRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRobot,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.GetRobotResponse>(
          this,
          Invocation.method(
            #getRobot,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.GetRobotResponse>(
          this,
          Invocation.method(
            #getRobot,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.GetRobotResponse>);
  @override
  _i4.ResponseFuture<_i13.GetRoverRentalRobotsResponse> getRoverRentalRobots(
    _i13.GetRoverRentalRobotsRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRoverRentalRobots,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.GetRoverRentalRobotsResponse>(
          this,
          Invocation.method(
            #getRoverRentalRobots,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.GetRoverRentalRobotsResponse>(
          this,
          Invocation.method(
            #getRoverRentalRobots,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.GetRoverRentalRobotsResponse>);
  @override
  _i4.ResponseFuture<_i13.GetRobotPartsResponse> getRobotParts(
    _i13.GetRobotPartsRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRobotParts,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.GetRobotPartsResponse>(
          this,
          Invocation.method(
            #getRobotParts,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.GetRobotPartsResponse>(
          this,
          Invocation.method(
            #getRobotParts,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.GetRobotPartsResponse>);
  @override
  _i4.ResponseFuture<_i13.GetRobotPartResponse> getRobotPart(
    _i13.GetRobotPartRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRobotPart,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.GetRobotPartResponse>(
          this,
          Invocation.method(
            #getRobotPart,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.GetRobotPartResponse>(
          this,
          Invocation.method(
            #getRobotPart,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.GetRobotPartResponse>);
  @override
  _i4.ResponseFuture<_i13.GetRobotPartLogsResponse> getRobotPartLogs(
    _i13.GetRobotPartLogsRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRobotPartLogs,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.GetRobotPartLogsResponse>(
          this,
          Invocation.method(
            #getRobotPartLogs,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.GetRobotPartLogsResponse>(
          this,
          Invocation.method(
            #getRobotPartLogs,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.GetRobotPartLogsResponse>);
  @override
  _i4.ResponseStream<_i13.TailRobotPartLogsResponse> tailRobotPartLogs(
    _i13.TailRobotPartLogsRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #tailRobotPartLogs,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseStream_3<_i13.TailRobotPartLogsResponse>(
          this,
          Invocation.method(
            #tailRobotPartLogs,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseStream_3<_i13.TailRobotPartLogsResponse>(
          this,
          Invocation.method(
            #tailRobotPartLogs,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseStream<_i13.TailRobotPartLogsResponse>);
  @override
  _i4.ResponseFuture<_i13.GetRobotPartHistoryResponse> getRobotPartHistory(
    _i13.GetRobotPartHistoryRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRobotPartHistory,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.GetRobotPartHistoryResponse>(
          this,
          Invocation.method(
            #getRobotPartHistory,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.GetRobotPartHistoryResponse>(
          this,
          Invocation.method(
            #getRobotPartHistory,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.GetRobotPartHistoryResponse>);
  @override
  _i4.ResponseFuture<_i13.UpdateRobotPartResponse> updateRobotPart(
    _i13.UpdateRobotPartRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRobotPart,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.UpdateRobotPartResponse>(
          this,
          Invocation.method(
            #updateRobotPart,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.UpdateRobotPartResponse>(
          this,
          Invocation.method(
            #updateRobotPart,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.UpdateRobotPartResponse>);
  @override
  _i4.ResponseFuture<_i13.NewRobotPartResponse> newRobotPart(
    _i13.NewRobotPartRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #newRobotPart,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.NewRobotPartResponse>(
          this,
          Invocation.method(
            #newRobotPart,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.NewRobotPartResponse>(
          this,
          Invocation.method(
            #newRobotPart,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.NewRobotPartResponse>);
  @override
  _i4.ResponseFuture<_i13.DeleteRobotPartResponse> deleteRobotPart(
    _i13.DeleteRobotPartRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRobotPart,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.DeleteRobotPartResponse>(
          this,
          Invocation.method(
            #deleteRobotPart,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.DeleteRobotPartResponse>(
          this,
          Invocation.method(
            #deleteRobotPart,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.DeleteRobotPartResponse>);
  @override
  _i4.ResponseFuture<_i13.MarkPartAsMainResponse> markPartAsMain(
    _i13.MarkPartAsMainRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #markPartAsMain,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.MarkPartAsMainResponse>(
          this,
          Invocation.method(
            #markPartAsMain,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.MarkPartAsMainResponse>(
          this,
          Invocation.method(
            #markPartAsMain,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.MarkPartAsMainResponse>);
  @override
  _i4.ResponseFuture<_i13.MarkPartForRestartResponse> markPartForRestart(
    _i13.MarkPartForRestartRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #markPartForRestart,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.MarkPartForRestartResponse>(
          this,
          Invocation.method(
            #markPartForRestart,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.MarkPartForRestartResponse>(
          this,
          Invocation.method(
            #markPartForRestart,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.MarkPartForRestartResponse>);
  @override
  _i4.ResponseFuture<_i13.CreateRobotPartSecretResponse> createRobotPartSecret(
    _i13.CreateRobotPartSecretRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createRobotPartSecret,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.CreateRobotPartSecretResponse>(
          this,
          Invocation.method(
            #createRobotPartSecret,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.CreateRobotPartSecretResponse>(
          this,
          Invocation.method(
            #createRobotPartSecret,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.CreateRobotPartSecretResponse>);
  @override
  _i4.ResponseFuture<_i13.DeleteRobotPartSecretResponse> deleteRobotPartSecret(
    _i13.DeleteRobotPartSecretRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRobotPartSecret,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.DeleteRobotPartSecretResponse>(
          this,
          Invocation.method(
            #deleteRobotPartSecret,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.DeleteRobotPartSecretResponse>(
          this,
          Invocation.method(
            #deleteRobotPartSecret,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.DeleteRobotPartSecretResponse>);
  @override
  _i4.ResponseFuture<_i13.ListRobotsResponse> listRobots(
    _i13.ListRobotsRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listRobots,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.ListRobotsResponse>(
          this,
          Invocation.method(
            #listRobots,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.ListRobotsResponse>(
          this,
          Invocation.method(
            #listRobots,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.ListRobotsResponse>);
  @override
  _i4.ResponseFuture<_i13.NewRobotResponse> newRobot(
    _i13.NewRobotRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #newRobot,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.NewRobotResponse>(
          this,
          Invocation.method(
            #newRobot,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.NewRobotResponse>(
          this,
          Invocation.method(
            #newRobot,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.NewRobotResponse>);
  @override
  _i4.ResponseFuture<_i13.UpdateRobotResponse> updateRobot(
    _i13.UpdateRobotRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRobot,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.UpdateRobotResponse>(
          this,
          Invocation.method(
            #updateRobot,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.UpdateRobotResponse>(
          this,
          Invocation.method(
            #updateRobot,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.UpdateRobotResponse>);
  @override
  _i4.ResponseFuture<_i13.DeleteRobotResponse> deleteRobot(
    _i13.DeleteRobotRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRobot,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.DeleteRobotResponse>(
          this,
          Invocation.method(
            #deleteRobot,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.DeleteRobotResponse>(
          this,
          Invocation.method(
            #deleteRobot,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.DeleteRobotResponse>);
  @override
  _i4.ResponseFuture<_i13.ListFragmentsResponse> listFragments(
    _i13.ListFragmentsRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listFragments,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.ListFragmentsResponse>(
          this,
          Invocation.method(
            #listFragments,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.ListFragmentsResponse>(
          this,
          Invocation.method(
            #listFragments,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.ListFragmentsResponse>);
  @override
  _i4.ResponseFuture<_i13.GetFragmentResponse> getFragment(
    _i13.GetFragmentRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFragment,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.GetFragmentResponse>(
          this,
          Invocation.method(
            #getFragment,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.GetFragmentResponse>(
          this,
          Invocation.method(
            #getFragment,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.GetFragmentResponse>);
  @override
  _i4.ResponseFuture<_i13.CreateFragmentResponse> createFragment(
    _i13.CreateFragmentRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFragment,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.CreateFragmentResponse>(
          this,
          Invocation.method(
            #createFragment,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.CreateFragmentResponse>(
          this,
          Invocation.method(
            #createFragment,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.CreateFragmentResponse>);
  @override
  _i4.ResponseFuture<_i13.UpdateFragmentResponse> updateFragment(
    _i13.UpdateFragmentRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFragment,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.UpdateFragmentResponse>(
          this,
          Invocation.method(
            #updateFragment,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.UpdateFragmentResponse>(
          this,
          Invocation.method(
            #updateFragment,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.UpdateFragmentResponse>);
  @override
  _i4.ResponseFuture<_i13.DeleteFragmentResponse> deleteFragment(
    _i13.DeleteFragmentRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFragment,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.DeleteFragmentResponse>(
          this,
          Invocation.method(
            #deleteFragment,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.DeleteFragmentResponse>(
          this,
          Invocation.method(
            #deleteFragment,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.DeleteFragmentResponse>);
  @override
  _i4.ResponseFuture<_i13.AddRoleResponse> addRole(
    _i13.AddRoleRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRole,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.AddRoleResponse>(
          this,
          Invocation.method(
            #addRole,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.AddRoleResponse>(
          this,
          Invocation.method(
            #addRole,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.AddRoleResponse>);
  @override
  _i4.ResponseFuture<_i13.RemoveRoleResponse> removeRole(
    _i13.RemoveRoleRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeRole,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.RemoveRoleResponse>(
          this,
          Invocation.method(
            #removeRole,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.RemoveRoleResponse>(
          this,
          Invocation.method(
            #removeRole,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.RemoveRoleResponse>);
  @override
  _i4.ResponseFuture<_i13.ListAuthorizationsResponse> listAuthorizations(
    _i13.ListAuthorizationsRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listAuthorizations,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.ListAuthorizationsResponse>(
          this,
          Invocation.method(
            #listAuthorizations,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.ListAuthorizationsResponse>(
          this,
          Invocation.method(
            #listAuthorizations,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.ListAuthorizationsResponse>);
  @override
  _i4.ResponseFuture<_i13.CheckPermissionsResponse> checkPermissions(
    _i13.CheckPermissionsRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkPermissions,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.CheckPermissionsResponse>(
          this,
          Invocation.method(
            #checkPermissions,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.CheckPermissionsResponse>(
          this,
          Invocation.method(
            #checkPermissions,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.CheckPermissionsResponse>);
  @override
  _i4.ResponseFuture<_i13.CreateModuleResponse> createModule(
    _i13.CreateModuleRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createModule,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.CreateModuleResponse>(
          this,
          Invocation.method(
            #createModule,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.CreateModuleResponse>(
          this,
          Invocation.method(
            #createModule,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.CreateModuleResponse>);
  @override
  _i4.ResponseFuture<_i13.UpdateModuleResponse> updateModule(
    _i13.UpdateModuleRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateModule,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.UpdateModuleResponse>(
          this,
          Invocation.method(
            #updateModule,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.UpdateModuleResponse>(
          this,
          Invocation.method(
            #updateModule,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.UpdateModuleResponse>);
  @override
  _i4.ResponseFuture<_i13.UploadModuleFileResponse> uploadModuleFile(
    _i8.Stream<_i13.UploadModuleFileRequest>? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadModuleFile,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.UploadModuleFileResponse>(
          this,
          Invocation.method(
            #uploadModuleFile,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.UploadModuleFileResponse>(
          this,
          Invocation.method(
            #uploadModuleFile,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.UploadModuleFileResponse>);
  @override
  _i4.ResponseFuture<_i13.GetModuleResponse> getModule(
    _i13.GetModuleRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getModule,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.GetModuleResponse>(
          this,
          Invocation.method(
            #getModule,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.GetModuleResponse>(
          this,
          Invocation.method(
            #getModule,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.GetModuleResponse>);
  @override
  _i4.ResponseFuture<_i13.ListModulesResponse> listModules(
    _i13.ListModulesRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listModules,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i13.ListModulesResponse>(
          this,
          Invocation.method(
            #listModules,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i13.ListModulesResponse>(
          this,
          Invocation.method(
            #listModules,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i13.ListModulesResponse>);
  @override
  _i3.ClientCall<Q, R> $createCall<Q, R>(
    _i9.ClientMethod<Q, R>? method,
    _i8.Stream<Q>? requests, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createCall,
          [
            method,
            requests,
          ],
          {#options: options},
        ),
        returnValue: _FakeClientCall_1<Q, R>(
          this,
          Invocation.method(
            #$createCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeClientCall_1<Q, R>(
          this,
          Invocation.method(
            #$createCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
      ) as _i3.ClientCall<Q, R>);
  @override
  _i4.ResponseFuture<R> $createUnaryCall<Q, R>(
    _i9.ClientMethod<Q, R>? method,
    Q? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createUnaryCall,
          [
            method,
            request,
          ],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<R>(
          this,
          Invocation.method(
            #$createUnaryCall,
            [
              method,
              request,
            ],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<R>(
          this,
          Invocation.method(
            #$createUnaryCall,
            [
              method,
              request,
            ],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<R>);
  @override
  _i4.ResponseStream<R> $createStreamingCall<Q, R>(
    _i9.ClientMethod<Q, R>? method,
    _i8.Stream<Q>? requests, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createStreamingCall,
          [
            method,
            requests,
          ],
          {#options: options},
        ),
        returnValue: _FakeResponseStream_3<R>(
          this,
          Invocation.method(
            #$createStreamingCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseStream_3<R>(
          this,
          Invocation.method(
            #$createStreamingCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseStream<R>);
}

/// A class which mocks [DataServiceClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockDataServiceClient extends _i1.Mock implements _i14.DataServiceClient {
  @override
  _i4.ResponseFuture<_i15.TabularDataByFilterResponse> tabularDataByFilter(
    _i15.TabularDataByFilterRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #tabularDataByFilter,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i15.TabularDataByFilterResponse>(
          this,
          Invocation.method(
            #tabularDataByFilter,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i15.TabularDataByFilterResponse>(
          this,
          Invocation.method(
            #tabularDataByFilter,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i15.TabularDataByFilterResponse>);
  @override
  _i4.ResponseFuture<_i15.BinaryDataByFilterResponse> binaryDataByFilter(
    _i15.BinaryDataByFilterRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #binaryDataByFilter,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i15.BinaryDataByFilterResponse>(
          this,
          Invocation.method(
            #binaryDataByFilter,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i15.BinaryDataByFilterResponse>(
          this,
          Invocation.method(
            #binaryDataByFilter,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i15.BinaryDataByFilterResponse>);
  @override
  _i4.ResponseFuture<_i15.BinaryDataByIDsResponse> binaryDataByIDs(
    _i15.BinaryDataByIDsRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #binaryDataByIDs,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i15.BinaryDataByIDsResponse>(
          this,
          Invocation.method(
            #binaryDataByIDs,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i15.BinaryDataByIDsResponse>(
          this,
          Invocation.method(
            #binaryDataByIDs,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i15.BinaryDataByIDsResponse>);
  @override
  _i4.ResponseFuture<_i15.DeleteTabularDataByFilterResponse> deleteTabularDataByFilter(
    _i15.DeleteTabularDataByFilterRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteTabularDataByFilter,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i15.DeleteTabularDataByFilterResponse>(
          this,
          Invocation.method(
            #deleteTabularDataByFilter,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i15.DeleteTabularDataByFilterResponse>(
          this,
          Invocation.method(
            #deleteTabularDataByFilter,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i15.DeleteTabularDataByFilterResponse>);
  @override
  _i4.ResponseFuture<_i15.DeleteBinaryDataByFilterResponse> deleteBinaryDataByFilter(
    _i15.DeleteBinaryDataByFilterRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteBinaryDataByFilter,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i15.DeleteBinaryDataByFilterResponse>(
          this,
          Invocation.method(
            #deleteBinaryDataByFilter,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i15.DeleteBinaryDataByFilterResponse>(
          this,
          Invocation.method(
            #deleteBinaryDataByFilter,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i15.DeleteBinaryDataByFilterResponse>);
  @override
  _i4.ResponseFuture<_i15.DeleteBinaryDataByIDsResponse> deleteBinaryDataByIDs(
    _i15.DeleteBinaryDataByIDsRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteBinaryDataByIDs,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i15.DeleteBinaryDataByIDsResponse>(
          this,
          Invocation.method(
            #deleteBinaryDataByIDs,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i15.DeleteBinaryDataByIDsResponse>(
          this,
          Invocation.method(
            #deleteBinaryDataByIDs,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i15.DeleteBinaryDataByIDsResponse>);
  @override
  _i4.ResponseFuture<_i15.AddTagsToBinaryDataByIDsResponse> addTagsToBinaryDataByIDs(
    _i15.AddTagsToBinaryDataByIDsRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTagsToBinaryDataByIDs,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i15.AddTagsToBinaryDataByIDsResponse>(
          this,
          Invocation.method(
            #addTagsToBinaryDataByIDs,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i15.AddTagsToBinaryDataByIDsResponse>(
          this,
          Invocation.method(
            #addTagsToBinaryDataByIDs,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i15.AddTagsToBinaryDataByIDsResponse>);
  @override
  _i4.ResponseFuture<_i15.AddTagsToBinaryDataByFilterResponse> addTagsToBinaryDataByFilter(
    _i15.AddTagsToBinaryDataByFilterRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTagsToBinaryDataByFilter,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i15.AddTagsToBinaryDataByFilterResponse>(
          this,
          Invocation.method(
            #addTagsToBinaryDataByFilter,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i15.AddTagsToBinaryDataByFilterResponse>(
          this,
          Invocation.method(
            #addTagsToBinaryDataByFilter,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i15.AddTagsToBinaryDataByFilterResponse>);
  @override
  _i4.ResponseFuture<_i15.RemoveTagsFromBinaryDataByIDsResponse> removeTagsFromBinaryDataByIDs(
    _i15.RemoveTagsFromBinaryDataByIDsRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeTagsFromBinaryDataByIDs,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i15.RemoveTagsFromBinaryDataByIDsResponse>(
          this,
          Invocation.method(
            #removeTagsFromBinaryDataByIDs,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i15.RemoveTagsFromBinaryDataByIDsResponse>(
          this,
          Invocation.method(
            #removeTagsFromBinaryDataByIDs,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i15.RemoveTagsFromBinaryDataByIDsResponse>);
  @override
  _i4.ResponseFuture<_i15.RemoveTagsFromBinaryDataByFilterResponse> removeTagsFromBinaryDataByFilter(
    _i15.RemoveTagsFromBinaryDataByFilterRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeTagsFromBinaryDataByFilter,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i15.RemoveTagsFromBinaryDataByFilterResponse>(
          this,
          Invocation.method(
            #removeTagsFromBinaryDataByFilter,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i15.RemoveTagsFromBinaryDataByFilterResponse>(
          this,
          Invocation.method(
            #removeTagsFromBinaryDataByFilter,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i15.RemoveTagsFromBinaryDataByFilterResponse>);
  @override
  _i4.ResponseFuture<_i15.TagsByFilterResponse> tagsByFilter(
    _i15.TagsByFilterRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #tagsByFilter,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i15.TagsByFilterResponse>(
          this,
          Invocation.method(
            #tagsByFilter,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i15.TagsByFilterResponse>(
          this,
          Invocation.method(
            #tagsByFilter,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i15.TagsByFilterResponse>);
  @override
  _i4.ResponseFuture<_i15.AddBoundingBoxToImageByIDResponse> addBoundingBoxToImageByID(
    _i15.AddBoundingBoxToImageByIDRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addBoundingBoxToImageByID,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i15.AddBoundingBoxToImageByIDResponse>(
          this,
          Invocation.method(
            #addBoundingBoxToImageByID,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i15.AddBoundingBoxToImageByIDResponse>(
          this,
          Invocation.method(
            #addBoundingBoxToImageByID,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i15.AddBoundingBoxToImageByIDResponse>);
  @override
  _i4.ResponseFuture<_i15.RemoveBoundingBoxFromImageByIDResponse> removeBoundingBoxFromImageByID(
    _i15.RemoveBoundingBoxFromImageByIDRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeBoundingBoxFromImageByID,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i15.RemoveBoundingBoxFromImageByIDResponse>(
          this,
          Invocation.method(
            #removeBoundingBoxFromImageByID,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i15.RemoveBoundingBoxFromImageByIDResponse>(
          this,
          Invocation.method(
            #removeBoundingBoxFromImageByID,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i15.RemoveBoundingBoxFromImageByIDResponse>);
  @override
  _i4.ResponseFuture<_i15.BoundingBoxLabelsByFilterResponse> boundingBoxLabelsByFilter(
    _i15.BoundingBoxLabelsByFilterRequest? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #boundingBoxLabelsByFilter,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<_i15.BoundingBoxLabelsByFilterResponse>(
          this,
          Invocation.method(
            #boundingBoxLabelsByFilter,
            [request],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<_i15.BoundingBoxLabelsByFilterResponse>(
          this,
          Invocation.method(
            #boundingBoxLabelsByFilter,
            [request],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<_i15.BoundingBoxLabelsByFilterResponse>);
  @override
  _i3.ClientCall<Q, R> $createCall<Q, R>(
    _i9.ClientMethod<Q, R>? method,
    _i8.Stream<Q>? requests, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createCall,
          [
            method,
            requests,
          ],
          {#options: options},
        ),
        returnValue: _FakeClientCall_1<Q, R>(
          this,
          Invocation.method(
            #$createCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeClientCall_1<Q, R>(
          this,
          Invocation.method(
            #$createCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
      ) as _i3.ClientCall<Q, R>);
  @override
  _i4.ResponseFuture<R> $createUnaryCall<Q, R>(
    _i9.ClientMethod<Q, R>? method,
    Q? request, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createUnaryCall,
          [
            method,
            request,
          ],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_2<R>(
          this,
          Invocation.method(
            #$createUnaryCall,
            [
              method,
              request,
            ],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseFuture_2<R>(
          this,
          Invocation.method(
            #$createUnaryCall,
            [
              method,
              request,
            ],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseFuture<R>);
  @override
  _i4.ResponseStream<R> $createStreamingCall<Q, R>(
    _i9.ClientMethod<Q, R>? method,
    _i8.Stream<Q>? requests, {
    _i3.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createStreamingCall,
          [
            method,
            requests,
          ],
          {#options: options},
        ),
        returnValue: _FakeResponseStream_3<R>(
          this,
          Invocation.method(
            #$createStreamingCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
        returnValueForMissingStub: _FakeResponseStream_3<R>(
          this,
          Invocation.method(
            #$createStreamingCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
      ) as _i4.ResponseStream<R>);
}

/// A class which mocks [PowerSensorClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockPowerSensorClient extends _i1.Mock implements _i16.PowerSensorClient {
  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  set name(String? _name) => super.noSuchMethod(
        Invocation.setter(
          #name,
          _name,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i5.ClientChannelBase get channel => (super.noSuchMethod(
        Invocation.getter(#channel),
        returnValue: _FakeClientChannelBase_4(
          this,
          Invocation.getter(#channel),
        ),
        returnValueForMissingStub: _FakeClientChannelBase_4(
          this,
          Invocation.getter(#channel),
        ),
      ) as _i5.ClientChannelBase);
  @override
  set channel(_i5.ClientChannelBase? _channel) => super.noSuchMethod(
        Invocation.setter(
          #channel,
          _channel,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i6.PowerSensorServiceClient get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakePowerSensorServiceClient_5(
          this,
          Invocation.getter(#client),
        ),
        returnValueForMissingStub: _FakePowerSensorServiceClient_5(
          this,
          Invocation.getter(#client),
        ),
      ) as _i6.PowerSensorServiceClient);
  @override
  _i8.Future<_i7.Voltage> voltage({Map<String, dynamic>? extra}) => (super.noSuchMethod(
        Invocation.method(
          #voltage,
          [],
          {#extra: extra},
        ),
        returnValue: _i8.Future<_i7.Voltage>.value(_FakeVoltage_6(
          this,
          Invocation.method(
            #voltage,
            [],
            {#extra: extra},
          ),
        )),
        returnValueForMissingStub: _i8.Future<_i7.Voltage>.value(_FakeVoltage_6(
          this,
          Invocation.method(
            #voltage,
            [],
            {#extra: extra},
          ),
        )),
      ) as _i8.Future<_i7.Voltage>);
  @override
  _i8.Future<_i7.Current> current({Map<String, dynamic>? extra}) => (super.noSuchMethod(
        Invocation.method(
          #current,
          [],
          {#extra: extra},
        ),
        returnValue: _i8.Future<_i7.Current>.value(_FakeCurrent_7(
          this,
          Invocation.method(
            #current,
            [],
            {#extra: extra},
          ),
        )),
        returnValueForMissingStub: _i8.Future<_i7.Current>.value(_FakeCurrent_7(
          this,
          Invocation.method(
            #current,
            [],
            {#extra: extra},
          ),
        )),
      ) as _i8.Future<_i7.Current>);
  @override
  _i8.Future<double> power({Map<String, dynamic>? extra}) => (super.noSuchMethod(
        Invocation.method(
          #power,
          [],
          {#extra: extra},
        ),
        returnValue: _i8.Future<double>.value(0.0),
        returnValueForMissingStub: _i8.Future<double>.value(0.0),
      ) as _i8.Future<double>);
  @override
  _i8.Future<Map<String, dynamic>> doCommand(Map<String, dynamic>? command) => (super.noSuchMethod(
        Invocation.method(
          #doCommand,
          [command],
        ),
        returnValue: _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub: _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);
  @override
  _i8.Future<Map<String, dynamic>> readings({Map<String, dynamic>? extra}) => (super.noSuchMethod(
        Invocation.method(
          #readings,
          [],
          {#extra: extra},
        ),
        returnValue: _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub: _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);
}
