// Mocks generated by Mockito 5.3.2 from annotations
// in viam_sdk/test/unit_test/mocks/service_clients_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:grpc/service_api.dart' as _i2;
import 'package:grpc/src/client/call.dart' as _i3;
import 'package:grpc/src/client/channel.dart' as _i18;
import 'package:grpc/src/client/connection.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:viam_sdk/src/gen/app/v1/app.pb.dart' as _i20;
import 'package:viam_sdk/src/gen/app/v1/app.pbgrpc.dart' as _i19;
import 'package:viam_sdk/src/gen/common/v1/common.pb.dart' as _i7;
import 'package:viam_sdk/src/gen/component/camera/v1/camera.pb.dart' as _i14;
import 'package:viam_sdk/src/gen/component/camera/v1/camera.pbgrpc.dart'
    as _i13;
import 'package:viam_sdk/src/gen/component/movementsensor/v1/movementsensor.pb.dart'
    as _i6;
import 'package:viam_sdk/src/gen/component/movementsensor/v1/movementsensor.pbgrpc.dart'
    as _i5;
import 'package:viam_sdk/src/gen/google/api/httpbody.pb.dart' as _i15;
import 'package:viam_sdk/src/gen/proto/stream/v1/stream.pb.dart' as _i17;
import 'package:viam_sdk/src/gen/proto/stream/v1/stream.pbgrpc.dart' as _i16;
import 'package:viam_sdk/src/gen/robot/v1/robot.pb.dart' as _i10;
import 'package:viam_sdk/src/gen/robot/v1/robot.pbgrpc.dart' as _i9;
import 'package:viam_sdk/src/gen/service/sensors/v1/sensors.pb.dart' as _i12;
import 'package:viam_sdk/src/gen/service/sensors/v1/sensors.pbgrpc.dart'
    as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponseFuture_0<R> extends _i1.SmartFake
    implements _i2.ResponseFuture<R> {
  _FakeResponseFuture_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClientCall_1<Q, R> extends _i1.SmartFake
    implements _i3.ClientCall<Q, R> {
  _FakeClientCall_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponseStream_2<R> extends _i1.SmartFake
    implements _i2.ResponseStream<R> {
  _FakeResponseStream_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClientConnection_3 extends _i1.SmartFake
    implements _i4.ClientConnection {
  _FakeClientConnection_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MovementSensorServiceClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovementSensorServiceClient extends _i1.Mock
    implements _i5.MovementSensorServiceClient {
  MockMovementSensorServiceClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ResponseFuture<_i6.GetLinearVelocityResponse> getLinearVelocity(
    _i6.GetLinearVelocityRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLinearVelocity,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i6.GetLinearVelocityResponse>(
          this,
          Invocation.method(
            #getLinearVelocity,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i6.GetLinearVelocityResponse>);
  @override
  _i2.ResponseFuture<_i6.GetAngularVelocityResponse> getAngularVelocity(
    _i6.GetAngularVelocityRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAngularVelocity,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i6.GetAngularVelocityResponse>(
          this,
          Invocation.method(
            #getAngularVelocity,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i6.GetAngularVelocityResponse>);
  @override
  _i2.ResponseFuture<_i6.GetCompassHeadingResponse> getCompassHeading(
    _i6.GetCompassHeadingRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompassHeading,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i6.GetCompassHeadingResponse>(
          this,
          Invocation.method(
            #getCompassHeading,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i6.GetCompassHeadingResponse>);
  @override
  _i2.ResponseFuture<_i6.GetOrientationResponse> getOrientation(
    _i6.GetOrientationRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrientation,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i6.GetOrientationResponse>(
          this,
          Invocation.method(
            #getOrientation,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i6.GetOrientationResponse>);
  @override
  _i2.ResponseFuture<_i6.GetPositionResponse> getPosition(
    _i6.GetPositionRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPosition,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i6.GetPositionResponse>(
          this,
          Invocation.method(
            #getPosition,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i6.GetPositionResponse>);
  @override
  _i2.ResponseFuture<_i6.GetPropertiesResponse> getProperties(
    _i6.GetPropertiesRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProperties,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i6.GetPropertiesResponse>(
          this,
          Invocation.method(
            #getProperties,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i6.GetPropertiesResponse>);
  @override
  _i2.ResponseFuture<_i6.GetAccuracyResponse> getAccuracy(
    _i6.GetAccuracyRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccuracy,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i6.GetAccuracyResponse>(
          this,
          Invocation.method(
            #getAccuracy,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i6.GetAccuracyResponse>);
  @override
  _i2.ResponseFuture<_i6.GetLinearAccelerationResponse> getLinearAcceleration(
    _i6.GetLinearAccelerationRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLinearAcceleration,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i6.GetLinearAccelerationResponse>(
          this,
          Invocation.method(
            #getLinearAcceleration,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i6.GetLinearAccelerationResponse>);
  @override
  _i2.ResponseFuture<_i7.DoCommandResponse> doCommand(
    _i7.DoCommandRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #doCommand,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i7.DoCommandResponse>(
          this,
          Invocation.method(
            #doCommand,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i7.DoCommandResponse>);
  @override
  _i3.ClientCall<Q, R> $createCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    _i8.Stream<Q>? requests, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createCall,
          [
            method,
            requests,
          ],
          {#options: options},
        ),
        returnValue: _FakeClientCall_1<Q, R>(
          this,
          Invocation.method(
            #$createCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
      ) as _i3.ClientCall<Q, R>);
  @override
  _i2.ResponseFuture<R> $createUnaryCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    Q? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createUnaryCall,
          [
            method,
            request,
          ],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<R>(
          this,
          Invocation.method(
            #$createUnaryCall,
            [
              method,
              request,
            ],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<R>);
  @override
  _i2.ResponseStream<R> $createStreamingCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    _i8.Stream<Q>? requests, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createStreamingCall,
          [
            method,
            requests,
          ],
          {#options: options},
        ),
        returnValue: _FakeResponseStream_2<R>(
          this,
          Invocation.method(
            #$createStreamingCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseStream<R>);
}

/// A class which mocks [RobotServiceClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockRobotServiceClient extends _i1.Mock
    implements _i9.RobotServiceClient {
  MockRobotServiceClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ResponseFuture<_i10.GetOperationsResponse> getOperations(
    _i10.GetOperationsRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOperations,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i10.GetOperationsResponse>(
          this,
          Invocation.method(
            #getOperations,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i10.GetOperationsResponse>);
  @override
  _i2.ResponseFuture<_i10.GetSessionsResponse> getSessions(
    _i10.GetSessionsRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSessions,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i10.GetSessionsResponse>(
          this,
          Invocation.method(
            #getSessions,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i10.GetSessionsResponse>);
  @override
  _i2.ResponseFuture<_i10.ResourceNamesResponse> resourceNames(
    _i10.ResourceNamesRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resourceNames,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i10.ResourceNamesResponse>(
          this,
          Invocation.method(
            #resourceNames,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i10.ResourceNamesResponse>);
  @override
  _i2.ResponseFuture<_i10.ResourceRPCSubtypesResponse> resourceRPCSubtypes(
    _i10.ResourceRPCSubtypesRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resourceRPCSubtypes,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i10.ResourceRPCSubtypesResponse>(
          this,
          Invocation.method(
            #resourceRPCSubtypes,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i10.ResourceRPCSubtypesResponse>);
  @override
  _i2.ResponseFuture<_i10.CancelOperationResponse> cancelOperation(
    _i10.CancelOperationRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelOperation,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i10.CancelOperationResponse>(
          this,
          Invocation.method(
            #cancelOperation,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i10.CancelOperationResponse>);
  @override
  _i2.ResponseFuture<_i10.BlockForOperationResponse> blockForOperation(
    _i10.BlockForOperationRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #blockForOperation,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i10.BlockForOperationResponse>(
          this,
          Invocation.method(
            #blockForOperation,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i10.BlockForOperationResponse>);
  @override
  _i2.ResponseFuture<_i10.DiscoverComponentsResponse> discoverComponents(
    _i10.DiscoverComponentsRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverComponents,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i10.DiscoverComponentsResponse>(
          this,
          Invocation.method(
            #discoverComponents,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i10.DiscoverComponentsResponse>);
  @override
  _i2.ResponseFuture<_i10.FrameSystemConfigResponse> frameSystemConfig(
    _i10.FrameSystemConfigRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #frameSystemConfig,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i10.FrameSystemConfigResponse>(
          this,
          Invocation.method(
            #frameSystemConfig,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i10.FrameSystemConfigResponse>);
  @override
  _i2.ResponseFuture<_i10.TransformPoseResponse> transformPose(
    _i10.TransformPoseRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transformPose,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i10.TransformPoseResponse>(
          this,
          Invocation.method(
            #transformPose,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i10.TransformPoseResponse>);
  @override
  _i2.ResponseFuture<_i10.TransformPCDResponse> transformPCD(
    _i10.TransformPCDRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transformPCD,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i10.TransformPCDResponse>(
          this,
          Invocation.method(
            #transformPCD,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i10.TransformPCDResponse>);
  @override
  _i2.ResponseFuture<_i10.GetStatusResponse> getStatus(
    _i10.GetStatusRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStatus,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i10.GetStatusResponse>(
          this,
          Invocation.method(
            #getStatus,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i10.GetStatusResponse>);
  @override
  _i2.ResponseStream<_i10.StreamStatusResponse> streamStatus(
    _i10.StreamStatusRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #streamStatus,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseStream_2<_i10.StreamStatusResponse>(
          this,
          Invocation.method(
            #streamStatus,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseStream<_i10.StreamStatusResponse>);
  @override
  _i2.ResponseFuture<_i10.StopAllResponse> stopAll(
    _i10.StopAllRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #stopAll,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i10.StopAllResponse>(
          this,
          Invocation.method(
            #stopAll,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i10.StopAllResponse>);
  @override
  _i2.ResponseFuture<_i10.StartSessionResponse> startSession(
    _i10.StartSessionRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startSession,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i10.StartSessionResponse>(
          this,
          Invocation.method(
            #startSession,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i10.StartSessionResponse>);
  @override
  _i2.ResponseFuture<_i10.SendSessionHeartbeatResponse> sendSessionHeartbeat(
    _i10.SendSessionHeartbeatRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendSessionHeartbeat,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i10.SendSessionHeartbeatResponse>(
          this,
          Invocation.method(
            #sendSessionHeartbeat,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i10.SendSessionHeartbeatResponse>);
  @override
  _i3.ClientCall<Q, R> $createCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    _i8.Stream<Q>? requests, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createCall,
          [
            method,
            requests,
          ],
          {#options: options},
        ),
        returnValue: _FakeClientCall_1<Q, R>(
          this,
          Invocation.method(
            #$createCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
      ) as _i3.ClientCall<Q, R>);
  @override
  _i2.ResponseFuture<R> $createUnaryCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    Q? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createUnaryCall,
          [
            method,
            request,
          ],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<R>(
          this,
          Invocation.method(
            #$createUnaryCall,
            [
              method,
              request,
            ],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<R>);
  @override
  _i2.ResponseStream<R> $createStreamingCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    _i8.Stream<Q>? requests, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createStreamingCall,
          [
            method,
            requests,
          ],
          {#options: options},
        ),
        returnValue: _FakeResponseStream_2<R>(
          this,
          Invocation.method(
            #$createStreamingCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseStream<R>);
}

/// A class which mocks [SensorsServiceClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSensorsServiceClient extends _i1.Mock
    implements _i11.SensorsServiceClient {
  MockSensorsServiceClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ResponseFuture<_i12.GetSensorsResponse> getSensors(
    _i12.GetSensorsRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSensors,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i12.GetSensorsResponse>(
          this,
          Invocation.method(
            #getSensors,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i12.GetSensorsResponse>);
  @override
  _i2.ResponseFuture<_i12.GetReadingsResponse> getReadings(
    _i12.GetReadingsRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReadings,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i12.GetReadingsResponse>(
          this,
          Invocation.method(
            #getReadings,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i12.GetReadingsResponse>);
  @override
  _i2.ResponseFuture<_i7.DoCommandResponse> doCommand(
    _i7.DoCommandRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #doCommand,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i7.DoCommandResponse>(
          this,
          Invocation.method(
            #doCommand,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i7.DoCommandResponse>);
  @override
  _i3.ClientCall<Q, R> $createCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    _i8.Stream<Q>? requests, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createCall,
          [
            method,
            requests,
          ],
          {#options: options},
        ),
        returnValue: _FakeClientCall_1<Q, R>(
          this,
          Invocation.method(
            #$createCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
      ) as _i3.ClientCall<Q, R>);
  @override
  _i2.ResponseFuture<R> $createUnaryCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    Q? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createUnaryCall,
          [
            method,
            request,
          ],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<R>(
          this,
          Invocation.method(
            #$createUnaryCall,
            [
              method,
              request,
            ],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<R>);
  @override
  _i2.ResponseStream<R> $createStreamingCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    _i8.Stream<Q>? requests, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createStreamingCall,
          [
            method,
            requests,
          ],
          {#options: options},
        ),
        returnValue: _FakeResponseStream_2<R>(
          this,
          Invocation.method(
            #$createStreamingCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseStream<R>);
}

/// A class which mocks [CameraServiceClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockCameraServiceClient extends _i1.Mock
    implements _i13.CameraServiceClient {
  MockCameraServiceClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ResponseFuture<_i14.GetImageResponse> getImage(
    _i14.GetImageRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getImage,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i14.GetImageResponse>(
          this,
          Invocation.method(
            #getImage,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i14.GetImageResponse>);
  @override
  _i2.ResponseFuture<_i15.HttpBody> renderFrame(
    _i14.RenderFrameRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #renderFrame,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i15.HttpBody>(
          this,
          Invocation.method(
            #renderFrame,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i15.HttpBody>);
  @override
  _i2.ResponseFuture<_i14.GetPointCloudResponse> getPointCloud(
    _i14.GetPointCloudRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPointCloud,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i14.GetPointCloudResponse>(
          this,
          Invocation.method(
            #getPointCloud,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i14.GetPointCloudResponse>);
  @override
  _i2.ResponseFuture<_i14.GetPropertiesResponse> getProperties(
    _i14.GetPropertiesRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProperties,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i14.GetPropertiesResponse>(
          this,
          Invocation.method(
            #getProperties,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i14.GetPropertiesResponse>);
  @override
  _i2.ResponseFuture<_i7.DoCommandResponse> doCommand(
    _i7.DoCommandRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #doCommand,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i7.DoCommandResponse>(
          this,
          Invocation.method(
            #doCommand,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i7.DoCommandResponse>);
  @override
  _i3.ClientCall<Q, R> $createCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    _i8.Stream<Q>? requests, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createCall,
          [
            method,
            requests,
          ],
          {#options: options},
        ),
        returnValue: _FakeClientCall_1<Q, R>(
          this,
          Invocation.method(
            #$createCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
      ) as _i3.ClientCall<Q, R>);
  @override
  _i2.ResponseFuture<R> $createUnaryCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    Q? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createUnaryCall,
          [
            method,
            request,
          ],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<R>(
          this,
          Invocation.method(
            #$createUnaryCall,
            [
              method,
              request,
            ],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<R>);
  @override
  _i2.ResponseStream<R> $createStreamingCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    _i8.Stream<Q>? requests, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createStreamingCall,
          [
            method,
            requests,
          ],
          {#options: options},
        ),
        returnValue: _FakeResponseStream_2<R>(
          this,
          Invocation.method(
            #$createStreamingCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseStream<R>);
}

/// A class which mocks [StreamServiceClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockStreamServiceClient extends _i1.Mock
    implements _i16.StreamServiceClient {
  MockStreamServiceClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ResponseFuture<_i17.ListStreamsResponse> listStreams(
    _i17.ListStreamsRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listStreams,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i17.ListStreamsResponse>(
          this,
          Invocation.method(
            #listStreams,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i17.ListStreamsResponse>);
  @override
  _i2.ResponseFuture<_i17.AddStreamResponse> addStream(
    _i17.AddStreamRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addStream,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i17.AddStreamResponse>(
          this,
          Invocation.method(
            #addStream,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i17.AddStreamResponse>);
  @override
  _i2.ResponseFuture<_i17.RemoveStreamResponse> removeStream(
    _i17.RemoveStreamRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeStream,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i17.RemoveStreamResponse>(
          this,
          Invocation.method(
            #removeStream,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i17.RemoveStreamResponse>);
  @override
  _i3.ClientCall<Q, R> $createCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    _i8.Stream<Q>? requests, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createCall,
          [
            method,
            requests,
          ],
          {#options: options},
        ),
        returnValue: _FakeClientCall_1<Q, R>(
          this,
          Invocation.method(
            #$createCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
      ) as _i3.ClientCall<Q, R>);
  @override
  _i2.ResponseFuture<R> $createUnaryCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    Q? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createUnaryCall,
          [
            method,
            request,
          ],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<R>(
          this,
          Invocation.method(
            #$createUnaryCall,
            [
              method,
              request,
            ],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<R>);
  @override
  _i2.ResponseStream<R> $createStreamingCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    _i8.Stream<Q>? requests, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createStreamingCall,
          [
            method,
            requests,
          ],
          {#options: options},
        ),
        returnValue: _FakeResponseStream_2<R>(
          this,
          Invocation.method(
            #$createStreamingCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseStream<R>);
}

/// A class which mocks [ClientChannelBase].
///
/// See the documentation for Mockito's code generation for more information.
class MockClientChannelBase extends _i1.Mock implements _i18.ClientChannelBase {
  MockClientChannelBase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Stream<_i4.ConnectionState> get onConnectionStateChanged =>
      (super.noSuchMethod(
        Invocation.getter(#onConnectionStateChanged),
        returnValue: _i8.Stream<_i4.ConnectionState>.empty(),
      ) as _i8.Stream<_i4.ConnectionState>);
  @override
  _i8.Future<void> shutdown() => (super.noSuchMethod(
        Invocation.method(
          #shutdown,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
  @override
  _i8.Future<void> terminate() => (super.noSuchMethod(
        Invocation.method(
          #terminate,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
  @override
  _i4.ClientConnection createConnection() => (super.noSuchMethod(
        Invocation.method(
          #createConnection,
          [],
        ),
        returnValue: _FakeClientConnection_3(
          this,
          Invocation.method(
            #createConnection,
            [],
          ),
        ),
      ) as _i4.ClientConnection);
  @override
  _i8.Future<_i4.ClientConnection> getConnection() => (super.noSuchMethod(
        Invocation.method(
          #getConnection,
          [],
        ),
        returnValue:
            _i8.Future<_i4.ClientConnection>.value(_FakeClientConnection_3(
          this,
          Invocation.method(
            #getConnection,
            [],
          ),
        )),
      ) as _i8.Future<_i4.ClientConnection>);
  @override
  _i3.ClientCall<Q, R> createCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    _i8.Stream<Q>? requests,
    _i2.CallOptions? options,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCall,
          [
            method,
            requests,
            options,
          ],
        ),
        returnValue: _FakeClientCall_1<Q, R>(
          this,
          Invocation.method(
            #createCall,
            [
              method,
              requests,
              options,
            ],
          ),
        ),
      ) as _i3.ClientCall<Q, R>);
}

/// A class which mocks [AppServiceClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppServiceClient extends _i1.Mock implements _i19.AppServiceClient {
  MockAppServiceClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ResponseFuture<_i20.CreateOrganizationResponse> createOrganization(
    _i20.CreateOrganizationRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrganization,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i20.CreateOrganizationResponse>(
          this,
          Invocation.method(
            #createOrganization,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i20.CreateOrganizationResponse>);
  @override
  _i2.ResponseFuture<_i20.ListOrganizationsResponse> listOrganizations(
    _i20.ListOrganizationsRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listOrganizations,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i20.ListOrganizationsResponse>(
          this,
          Invocation.method(
            #listOrganizations,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i20.ListOrganizationsResponse>);
  @override
  _i2.ResponseFuture<_i20.GetOrganizationResponse> getOrganization(
    _i20.GetOrganizationRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrganization,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i20.GetOrganizationResponse>(
          this,
          Invocation.method(
            #getOrganization,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i20.GetOrganizationResponse>);
  @override
  _i2.ResponseFuture<_i20.UpdateOrganizationResponse> updateOrganization(
    _i20.UpdateOrganizationRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOrganization,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i20.UpdateOrganizationResponse>(
          this,
          Invocation.method(
            #updateOrganization,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i20.UpdateOrganizationResponse>);
  @override
  _i2.ResponseFuture<_i20.DeleteOrganizationResponse> deleteOrganization(
    _i20.DeleteOrganizationRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteOrganization,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i20.DeleteOrganizationResponse>(
          this,
          Invocation.method(
            #deleteOrganization,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i20.DeleteOrganizationResponse>);
  @override
  _i2.ResponseFuture<_i20.ListOrganizationMembersResponse>
      listOrganizationMembers(
    _i20.ListOrganizationMembersRequest? request, {
    _i2.CallOptions? options,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #listOrganizationMembers,
              [request],
              {#options: options},
            ),
            returnValue:
                _FakeResponseFuture_0<_i20.ListOrganizationMembersResponse>(
              this,
              Invocation.method(
                #listOrganizationMembers,
                [request],
                {#options: options},
              ),
            ),
          ) as _i2.ResponseFuture<_i20.ListOrganizationMembersResponse>);
  @override
  _i2.ResponseFuture<_i20.CreateOrganizationInviteResponse>
      createOrganizationInvite(
    _i20.CreateOrganizationInviteRequest? request, {
    _i2.CallOptions? options,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #createOrganizationInvite,
              [request],
              {#options: options},
            ),
            returnValue:
                _FakeResponseFuture_0<_i20.CreateOrganizationInviteResponse>(
              this,
              Invocation.method(
                #createOrganizationInvite,
                [request],
                {#options: options},
              ),
            ),
          ) as _i2.ResponseFuture<_i20.CreateOrganizationInviteResponse>);
  @override
  _i2.ResponseFuture<_i20.DeleteOrganizationMemberResponse>
      deleteOrganizationMember(
    _i20.DeleteOrganizationMemberRequest? request, {
    _i2.CallOptions? options,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #deleteOrganizationMember,
              [request],
              {#options: options},
            ),
            returnValue:
                _FakeResponseFuture_0<_i20.DeleteOrganizationMemberResponse>(
              this,
              Invocation.method(
                #deleteOrganizationMember,
                [request],
                {#options: options},
              ),
            ),
          ) as _i2.ResponseFuture<_i20.DeleteOrganizationMemberResponse>);
  @override
  _i2.ResponseFuture<_i20.DeleteOrganizationInviteResponse>
      deleteOrganizationInvite(
    _i20.DeleteOrganizationInviteRequest? request, {
    _i2.CallOptions? options,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #deleteOrganizationInvite,
              [request],
              {#options: options},
            ),
            returnValue:
                _FakeResponseFuture_0<_i20.DeleteOrganizationInviteResponse>(
              this,
              Invocation.method(
                #deleteOrganizationInvite,
                [request],
                {#options: options},
              ),
            ),
          ) as _i2.ResponseFuture<_i20.DeleteOrganizationInviteResponse>);
  @override
  _i2.ResponseFuture<_i20.ResendOrganizationInviteResponse>
      resendOrganizationInvite(
    _i20.ResendOrganizationInviteRequest? request, {
    _i2.CallOptions? options,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #resendOrganizationInvite,
              [request],
              {#options: options},
            ),
            returnValue:
                _FakeResponseFuture_0<_i20.ResendOrganizationInviteResponse>(
              this,
              Invocation.method(
                #resendOrganizationInvite,
                [request],
                {#options: options},
              ),
            ),
          ) as _i2.ResponseFuture<_i20.ResendOrganizationInviteResponse>);
  @override
  _i2.ResponseFuture<_i20.CreateLocationResponse> createLocation(
    _i20.CreateLocationRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createLocation,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i20.CreateLocationResponse>(
          this,
          Invocation.method(
            #createLocation,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i20.CreateLocationResponse>);
  @override
  _i2.ResponseFuture<_i20.GetLocationResponse> getLocation(
    _i20.GetLocationRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocation,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i20.GetLocationResponse>(
          this,
          Invocation.method(
            #getLocation,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i20.GetLocationResponse>);
  @override
  _i2.ResponseFuture<_i20.UpdateLocationResponse> updateLocation(
    _i20.UpdateLocationRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLocation,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i20.UpdateLocationResponse>(
          this,
          Invocation.method(
            #updateLocation,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i20.UpdateLocationResponse>);
  @override
  _i2.ResponseFuture<_i20.DeleteLocationResponse> deleteLocation(
    _i20.DeleteLocationRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteLocation,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i20.DeleteLocationResponse>(
          this,
          Invocation.method(
            #deleteLocation,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i20.DeleteLocationResponse>);
  @override
  _i2.ResponseFuture<_i20.ListLocationsResponse> listLocations(
    _i20.ListLocationsRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listLocations,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i20.ListLocationsResponse>(
          this,
          Invocation.method(
            #listLocations,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i20.ListLocationsResponse>);
  @override
  _i2.ResponseFuture<_i20.ShareLocationResponse> shareLocation(
    _i20.ShareLocationRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #shareLocation,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i20.ShareLocationResponse>(
          this,
          Invocation.method(
            #shareLocation,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i20.ShareLocationResponse>);
  @override
  _i2.ResponseFuture<_i20.UnshareLocationResponse> unshareLocation(
    _i20.UnshareLocationRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #unshareLocation,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i20.UnshareLocationResponse>(
          this,
          Invocation.method(
            #unshareLocation,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i20.UnshareLocationResponse>);
  @override
  _i2.ResponseFuture<_i20.LocationAuthResponse> locationAuth(
    _i20.LocationAuthRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #locationAuth,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i20.LocationAuthResponse>(
          this,
          Invocation.method(
            #locationAuth,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i20.LocationAuthResponse>);
  @override
  _i2.ResponseFuture<_i20.CreateLocationSecretResponse> createLocationSecret(
    _i20.CreateLocationSecretRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createLocationSecret,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i20.CreateLocationSecretResponse>(
          this,
          Invocation.method(
            #createLocationSecret,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i20.CreateLocationSecretResponse>);
  @override
  _i2.ResponseFuture<_i20.DeleteLocationSecretResponse> deleteLocationSecret(
    _i20.DeleteLocationSecretRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteLocationSecret,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i20.DeleteLocationSecretResponse>(
          this,
          Invocation.method(
            #deleteLocationSecret,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i20.DeleteLocationSecretResponse>);
  @override
  _i2.ResponseFuture<_i20.GetRobotResponse> getRobot(
    _i20.GetRobotRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRobot,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i20.GetRobotResponse>(
          this,
          Invocation.method(
            #getRobot,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i20.GetRobotResponse>);
  @override
  _i2.ResponseFuture<_i20.GetRoverRentalRobotsResponse> getRoverRentalRobots(
    _i20.GetRoverRentalRobotsRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRoverRentalRobots,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i20.GetRoverRentalRobotsResponse>(
          this,
          Invocation.method(
            #getRoverRentalRobots,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i20.GetRoverRentalRobotsResponse>);
  @override
  _i2.ResponseFuture<_i20.GetRobotPartsResponse> getRobotParts(
    _i20.GetRobotPartsRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRobotParts,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i20.GetRobotPartsResponse>(
          this,
          Invocation.method(
            #getRobotParts,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i20.GetRobotPartsResponse>);
  @override
  _i2.ResponseFuture<_i20.GetRobotPartResponse> getRobotPart(
    _i20.GetRobotPartRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRobotPart,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i20.GetRobotPartResponse>(
          this,
          Invocation.method(
            #getRobotPart,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i20.GetRobotPartResponse>);
  @override
  _i2.ResponseFuture<_i20.GetRobotPartLogsResponse> getRobotPartLogs(
    _i20.GetRobotPartLogsRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRobotPartLogs,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i20.GetRobotPartLogsResponse>(
          this,
          Invocation.method(
            #getRobotPartLogs,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i20.GetRobotPartLogsResponse>);
  @override
  _i2.ResponseStream<_i20.TailRobotPartLogsResponse> tailRobotPartLogs(
    _i20.TailRobotPartLogsRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #tailRobotPartLogs,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseStream_2<_i20.TailRobotPartLogsResponse>(
          this,
          Invocation.method(
            #tailRobotPartLogs,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseStream<_i20.TailRobotPartLogsResponse>);
  @override
  _i2.ResponseFuture<_i20.GetRobotPartHistoryResponse> getRobotPartHistory(
    _i20.GetRobotPartHistoryRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRobotPartHistory,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i20.GetRobotPartHistoryResponse>(
          this,
          Invocation.method(
            #getRobotPartHistory,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i20.GetRobotPartHistoryResponse>);
  @override
  _i2.ResponseFuture<_i20.UpdateRobotPartResponse> updateRobotPart(
    _i20.UpdateRobotPartRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRobotPart,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i20.UpdateRobotPartResponse>(
          this,
          Invocation.method(
            #updateRobotPart,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i20.UpdateRobotPartResponse>);
  @override
  _i2.ResponseFuture<_i20.NewRobotPartResponse> newRobotPart(
    _i20.NewRobotPartRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #newRobotPart,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i20.NewRobotPartResponse>(
          this,
          Invocation.method(
            #newRobotPart,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i20.NewRobotPartResponse>);
  @override
  _i2.ResponseFuture<_i20.DeleteRobotPartResponse> deleteRobotPart(
    _i20.DeleteRobotPartRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRobotPart,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i20.DeleteRobotPartResponse>(
          this,
          Invocation.method(
            #deleteRobotPart,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i20.DeleteRobotPartResponse>);
  @override
  _i2.ResponseFuture<_i20.MarkPartAsMainResponse> markPartAsMain(
    _i20.MarkPartAsMainRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #markPartAsMain,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i20.MarkPartAsMainResponse>(
          this,
          Invocation.method(
            #markPartAsMain,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i20.MarkPartAsMainResponse>);
  @override
  _i2.ResponseFuture<_i20.MarkPartForRestartResponse> markPartForRestart(
    _i20.MarkPartForRestartRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #markPartForRestart,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i20.MarkPartForRestartResponse>(
          this,
          Invocation.method(
            #markPartForRestart,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i20.MarkPartForRestartResponse>);
  @override
  _i2.ResponseFuture<_i20.CreateRobotPartSecretResponse> createRobotPartSecret(
    _i20.CreateRobotPartSecretRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createRobotPartSecret,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i20.CreateRobotPartSecretResponse>(
          this,
          Invocation.method(
            #createRobotPartSecret,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i20.CreateRobotPartSecretResponse>);
  @override
  _i2.ResponseFuture<_i20.DeleteRobotPartSecretResponse> deleteRobotPartSecret(
    _i20.DeleteRobotPartSecretRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRobotPartSecret,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i20.DeleteRobotPartSecretResponse>(
          this,
          Invocation.method(
            #deleteRobotPartSecret,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i20.DeleteRobotPartSecretResponse>);
  @override
  _i2.ResponseFuture<_i20.ListRobotsResponse> listRobots(
    _i20.ListRobotsRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listRobots,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i20.ListRobotsResponse>(
          this,
          Invocation.method(
            #listRobots,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i20.ListRobotsResponse>);
  @override
  _i2.ResponseFuture<_i20.NewRobotResponse> newRobot(
    _i20.NewRobotRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #newRobot,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i20.NewRobotResponse>(
          this,
          Invocation.method(
            #newRobot,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i20.NewRobotResponse>);
  @override
  _i2.ResponseFuture<_i20.UpdateRobotResponse> updateRobot(
    _i20.UpdateRobotRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRobot,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i20.UpdateRobotResponse>(
          this,
          Invocation.method(
            #updateRobot,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i20.UpdateRobotResponse>);
  @override
  _i2.ResponseFuture<_i20.DeleteRobotResponse> deleteRobot(
    _i20.DeleteRobotRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRobot,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i20.DeleteRobotResponse>(
          this,
          Invocation.method(
            #deleteRobot,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i20.DeleteRobotResponse>);
  @override
  _i2.ResponseFuture<_i20.ListFragmentsResponse> listFragments(
    _i20.ListFragmentsRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listFragments,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i20.ListFragmentsResponse>(
          this,
          Invocation.method(
            #listFragments,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i20.ListFragmentsResponse>);
  @override
  _i2.ResponseFuture<_i20.GetFragmentResponse> getFragment(
    _i20.GetFragmentRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFragment,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i20.GetFragmentResponse>(
          this,
          Invocation.method(
            #getFragment,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i20.GetFragmentResponse>);
  @override
  _i2.ResponseFuture<_i20.CreateFragmentResponse> createFragment(
    _i20.CreateFragmentRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFragment,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i20.CreateFragmentResponse>(
          this,
          Invocation.method(
            #createFragment,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i20.CreateFragmentResponse>);
  @override
  _i2.ResponseFuture<_i20.UpdateFragmentResponse> updateFragment(
    _i20.UpdateFragmentRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFragment,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i20.UpdateFragmentResponse>(
          this,
          Invocation.method(
            #updateFragment,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i20.UpdateFragmentResponse>);
  @override
  _i2.ResponseFuture<_i20.DeleteFragmentResponse> deleteFragment(
    _i20.DeleteFragmentRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFragment,
          [request],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<_i20.DeleteFragmentResponse>(
          this,
          Invocation.method(
            #deleteFragment,
            [request],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<_i20.DeleteFragmentResponse>);
  @override
  _i3.ClientCall<Q, R> $createCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    _i8.Stream<Q>? requests, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createCall,
          [
            method,
            requests,
          ],
          {#options: options},
        ),
        returnValue: _FakeClientCall_1<Q, R>(
          this,
          Invocation.method(
            #$createCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
      ) as _i3.ClientCall<Q, R>);
  @override
  _i2.ResponseFuture<R> $createUnaryCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    Q? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createUnaryCall,
          [
            method,
            request,
          ],
          {#options: options},
        ),
        returnValue: _FakeResponseFuture_0<R>(
          this,
          Invocation.method(
            #$createUnaryCall,
            [
              method,
              request,
            ],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseFuture<R>);
  @override
  _i2.ResponseStream<R> $createStreamingCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    _i8.Stream<Q>? requests, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$createStreamingCall,
          [
            method,
            requests,
          ],
          {#options: options},
        ),
        returnValue: _FakeResponseStream_2<R>(
          this,
          Invocation.method(
            #$createStreamingCall,
            [
              method,
              requests,
            ],
            {#options: options},
          ),
        ),
      ) as _i2.ResponseStream<R>);
}
