/// The proto definitions for arm
/// {@category Protobuf Definitions}
library viam_protos.component.arm;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/component/arm/v1/arm.pb.dart';
export '../../../src/gen/component/arm/v1/arm.pbenum.dart';
export '../../../src/gen/component/arm/v1/arm.pbgrpc.dart';
export '../../../src/gen/component/arm/v1/arm.pbjson.dart';
