/// The proto definitions for audioin
/// {@category Protobuf Definitions}
library viam_protos.component.audioin;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/component/audioin/v1/audioin.pb.dart';
export '../../../src/gen/component/audioin/v1/audioin.pbenum.dart';
export '../../../src/gen/component/audioin/v1/audioin.pbgrpc.dart';
export '../../../src/gen/component/audioin/v1/audioin.pbjson.dart';
