/// The proto definitions for audioinput
/// {@category Protobuf Definitions}
library viam_protos.component.audioinput;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/component/audioinput/v1/audioinput.pbjson.dart';
export '../../../src/gen/component/audioinput/v1/audioinput.pb.dart';
export '../../../src/gen/component/audioinput/v1/audioinput.pbgrpc.dart';
export '../../../src/gen/component/audioinput/v1/audioinput.pbenum.dart';
