/// The proto definitions for audioout
/// {@category Protobuf Definitions}
library viam_protos.component.audioout;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/component/audioout/v1/audioout.pb.dart';
export '../../../src/gen/component/audioout/v1/audioout.pbenum.dart';
export '../../../src/gen/component/audioout/v1/audioout.pbgrpc.dart';
export '../../../src/gen/component/audioout/v1/audioout.pbjson.dart';
