/// The proto definitions for base
/// {@category Protobuf Definitions}
library viam_protos.component.base;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/component/base/v1/base.pbjson.dart';
export '../../../src/gen/component/base/v1/base.pbgrpc.dart';
export '../../../src/gen/component/base/v1/base.pbenum.dart';
export '../../../src/gen/component/base/v1/base.pb.dart';
