/// The proto definitions for board
/// {@category Protobuf Definitions}
library viam_protos.component.board;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/component/board/v1/board.pb.dart';
export '../../../src/gen/component/board/v1/board.pbgrpc.dart';
export '../../../src/gen/component/board/v1/board.pbjson.dart';
export '../../../src/gen/component/board/v1/board.pbenum.dart';
