/// The proto definitions for button
/// {@category Protobuf Definitions}
library viam_protos.component.button;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/component/button/v1/button.pb.dart';
export '../../../src/gen/component/button/v1/button.pbenum.dart';
export '../../../src/gen/component/button/v1/button.pbgrpc.dart';
export '../../../src/gen/component/button/v1/button.pbjson.dart';
