/// The proto definitions for camera
/// {@category Protobuf Definitions}
library viam_protos.component.camera;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/component/camera/v1/camera.pbjson.dart';
export '../../../src/gen/component/camera/v1/camera.pb.dart';
export '../../../src/gen/component/camera/v1/camera.pbgrpc.dart';
export '../../../src/gen/component/camera/v1/camera.pbenum.dart';
