/// The proto definitions for encoder
/// {@category Protobuf Definitions}
library viam_protos.component.encoder;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/component/encoder/v1/encoder.pbjson.dart';
export '../../../src/gen/component/encoder/v1/encoder.pbgrpc.dart';
export '../../../src/gen/component/encoder/v1/encoder.pb.dart';
export '../../../src/gen/component/encoder/v1/encoder.pbenum.dart';
