/// The proto definitions for gantry
/// {@category Protobuf Definitions}
library viam_protos.component.gantry;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/component/gantry/v1/gantry.pb.dart';
export '../../../src/gen/component/gantry/v1/gantry.pbenum.dart';
export '../../../src/gen/component/gantry/v1/gantry.pbgrpc.dart';
export '../../../src/gen/component/gantry/v1/gantry.pbjson.dart';
