/// The proto definitions for input_controller
/// {@category Protobuf Definitions}
library viam_protos.component.input_controller;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/component/inputcontroller/v1/input_controller.pb.dart';
export '../../../src/gen/component/inputcontroller/v1/input_controller.pbenum.dart';
export '../../../src/gen/component/inputcontroller/v1/input_controller.pbjson.dart';
export '../../../src/gen/component/inputcontroller/v1/input_controller.pbgrpc.dart';
