/// The proto definitions for motor
/// {@category Protobuf Definitions}
library viam_protos.component.motor;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/component/motor/v1/motor.pbgrpc.dart';
export '../../../src/gen/component/motor/v1/motor.pbjson.dart';
export '../../../src/gen/component/motor/v1/motor.pbenum.dart';
export '../../../src/gen/component/motor/v1/motor.pb.dart';
