/// The proto definitions for movementsensor
/// {@category Protobuf Definitions}
library viam_protos.component.movementsensor;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/component/movementsensor/v1/movementsensor.pbjson.dart';
export '../../../src/gen/component/movementsensor/v1/movementsensor.pbgrpc.dart';
export '../../../src/gen/component/movementsensor/v1/movementsensor.pb.dart';
export '../../../src/gen/component/movementsensor/v1/movementsensor.pbenum.dart';
