/// The proto definitions for pose_tracker
/// {@category Protobuf Definitions}
library viam_protos.component.pose_tracker;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/component/posetracker/v1/pose_tracker.pb.dart';
export '../../../src/gen/component/posetracker/v1/pose_tracker.pbenum.dart';
export '../../../src/gen/component/posetracker/v1/pose_tracker.pbgrpc.dart';
export '../../../src/gen/component/posetracker/v1/pose_tracker.pbjson.dart';
