/// The proto definitions for powersensor
/// {@category Protobuf Definitions}
library viam_protos.component.powersensor;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/component/powersensor/v1/powersensor.pb.dart';
export '../../../src/gen/component/powersensor/v1/powersensor.pbjson.dart';
export '../../../src/gen/component/powersensor/v1/powersensor.pbgrpc.dart';
export '../../../src/gen/component/powersensor/v1/powersensor.pbenum.dart';
