/// The proto definitions for sensor
/// {@category Protobuf Definitions}
library viam_protos.component.sensor;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/component/sensor/v1/sensor.pbenum.dart';
export '../../../src/gen/component/sensor/v1/sensor.pb.dart';
export '../../../src/gen/component/sensor/v1/sensor.pbjson.dart';
export '../../../src/gen/component/sensor/v1/sensor.pbgrpc.dart';
