/// The proto definitions for servo
/// {@category Protobuf Definitions}
library viam_protos.component.servo;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/component/servo/v1/servo.pbjson.dart';
export '../../../src/gen/component/servo/v1/servo.pbgrpc.dart';
export '../../../src/gen/component/servo/v1/servo.pb.dart';
export '../../../src/gen/component/servo/v1/servo.pbenum.dart';
