/// The proto definitions for switch
/// {@category Protobuf Definitions}
library viam_protos.component.nswitch;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/component/nswitch/v1/switch.pb.dart';
export '../../../src/gen/component/nswitch/v1/switch.pbenum.dart';
export '../../../src/gen/component/nswitch/v1/switch.pbgrpc.dart';
export '../../../src/gen/component/nswitch/v1/switch.pbjson.dart';
