/// The proto definitions for data_manager
/// {@category Protobuf Definitions}
library viam_protos.service.data_manager;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/service/datamanager/v1/data_manager.pbgrpc.dart';
export '../../../src/gen/service/datamanager/v1/data_manager.pbjson.dart';
export '../../../src/gen/service/datamanager/v1/data_manager.pbenum.dart';
export '../../../src/gen/service/datamanager/v1/data_manager.pb.dart';
