/// The proto definitions for discovery
/// {@category Protobuf Definitions}
library viam_protos.service.discovery;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/service/discovery/v1/discovery.pb.dart';
export '../../../src/gen/service/discovery/v1/discovery.pbenum.dart';
export '../../../src/gen/service/discovery/v1/discovery.pbgrpc.dart';
export '../../../src/gen/service/discovery/v1/discovery.pbjson.dart';
