/// The proto definitions for generic
/// {@category Protobuf Definitions}
library viam_protos.service.generic;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/service/generic/v1/generic.pb.dart';
export '../../../src/gen/service/generic/v1/generic.pbenum.dart';
export '../../../src/gen/service/generic/v1/generic.pbgrpc.dart';
export '../../../src/gen/service/generic/v1/generic.pbjson.dart';
