/// The proto definitions for mlmodel
/// {@category Protobuf Definitions}
library viam_protos.service.mlmodel;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/service/mlmodel/v1/mlmodel.pb.dart';
export '../../../src/gen/service/mlmodel/v1/mlmodel.pbenum.dart';
export '../../../src/gen/service/mlmodel/v1/mlmodel.pbjson.dart';
export '../../../src/gen/service/mlmodel/v1/mlmodel.pbgrpc.dart';
