/// The proto definitions for motion
/// {@category Protobuf Definitions}
library viam_protos.service.motion;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/service/motion/v1/motion.pb.dart';
export '../../../src/gen/service/motion/v1/motion.pbjson.dart';
export '../../../src/gen/service/motion/v1/motion.pbenum.dart';
export '../../../src/gen/service/motion/v1/motion.pbgrpc.dart';
