/// The proto definitions for navigation
/// {@category Protobuf Definitions}
library viam_protos.service.navigation;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/service/navigation/v1/navigation.pbjson.dart';
export '../../../src/gen/service/navigation/v1/navigation.pbenum.dart';
export '../../../src/gen/service/navigation/v1/navigation.pbgrpc.dart';
export '../../../src/gen/service/navigation/v1/navigation.pb.dart';
