/// The proto definitions for sensors
/// {@category Protobuf Definitions}
library viam_protos.service.sensors;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/service/sensors/v1/sensors.pb.dart';
export '../../../src/gen/service/sensors/v1/sensors.pbenum.dart';
export '../../../src/gen/service/sensors/v1/sensors.pbgrpc.dart';
export '../../../src/gen/service/sensors/v1/sensors.pbjson.dart';
