/// The proto definitions for shell
/// {@category Protobuf Definitions}
library viam_protos.service.shell;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/service/shell/v1/shell.pb.dart';
export '../../../src/gen/service/shell/v1/shell.pbenum.dart';
export '../../../src/gen/service/shell/v1/shell.pbgrpc.dart';
export '../../../src/gen/service/shell/v1/shell.pbjson.dart';
