/// The proto definitions for slam
/// {@category Protobuf Definitions}
library viam_protos.service.slam;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/service/slam/v1/slam.pbenum.dart';
export '../../../src/gen/service/slam/v1/slam.pbgrpc.dart';
export '../../../src/gen/service/slam/v1/slam.pbjson.dart';
export '../../../src/gen/service/slam/v1/slam.pb.dart';
