/// The proto definitions for video
/// {@category Protobuf Definitions}
library viam_protos.service.video;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/service/video/v1/video.pb.dart';
export '../../../src/gen/service/video/v1/video.pbenum.dart';
export '../../../src/gen/service/video/v1/video.pbgrpc.dart';
export '../../../src/gen/service/video/v1/video.pbjson.dart';
