/// The proto definitions for vision
/// {@category Protobuf Definitions}
library viam_protos.service.vision;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/service/vision/v1/vision.pbgrpc.dart';
export '../../../src/gen/service/vision/v1/vision.pb.dart';
export '../../../src/gen/service/vision/v1/vision.pbjson.dart';
export '../../../src/gen/service/vision/v1/vision.pbenum.dart';
