/// The proto definitions for world_state_store
/// {@category Protobuf Definitions}
library viam_protos.service.world_state_store;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/service/worldstatestore/v1/world_state_store.pb.dart';
export '../../../src/gen/service/worldstatestore/v1/world_state_store.pbenum.dart';
export '../../../src/gen/service/worldstatestore/v1/world_state_store.pbgrpc.dart';
export '../../../src/gen/service/worldstatestore/v1/world_state_store.pbjson.dart';
