import 'dart:io';

import 'package:collection/collection.dart';
import 'package:path/path.dart' as path;

String get _protoPath {
  return '${Directory.current.uri.toFilePath()}lib${Platform.pathSeparator}src${Platform.pathSeparator}gen${Platform.pathSeparator}';
}

String get _newProtoPath {
  return '${Directory.current.uri.toFilePath()}lib${Platform.pathSeparator}protos${Platform.pathSeparator}';
}

/// Get a list of all proto files that we care about
Future<Iterable<File>> _getFiles() async {
  const protoDirs = ['app', 'common', 'component', 'module', 'robot', 'service'];
  final List<File> files = [];
  for (final protoDir in protoDirs) {
    final dir = Directory('$_protoPath$protoDir');
    final List<FileSystemEntity> entities = await dir.list(recursive: true).toList();
    files.addAll(entities.whereType<File>());
  }
  return files;
}

/// Get the directory structure.
/// Key: package name (e.g. app, common, component, ...)
/// Value: All the files that should live inside the directory
Map<String, Iterable<File>> _getDirStructure(Iterable<File> files) {
  final dirNameToFiles = <String, List<File>>{};
  for (final file in files) {
    final path = file.parent.parent.path.replaceAll(_protoPath, '');
    final dirName = path.split(Platform.pathSeparator).first;
    final list = dirNameToFiles[dirName] ?? [];
    list.add(file);
    dirNameToFiles[dirName] = list;
  }
  return dirNameToFiles;
}

/// Create the directories at the new proto path
Future<void> _createDirs(Iterable<String> dirNames) async {
  for (final dirName in dirNames) {
    await Directory('$_newProtoPath$dirName').create(recursive: true);
  }
}

/// Get the new file structure
/// Key: The new filename for the proto library (e.g. arm.dart, vision.dart)
/// Value: All the files to export (e.g. arm.pb.dart, vision.pbgrpc.dart)
Map<String, Set<File>> _getFileStructure(Iterable<File> files) {
  final fileNameToExports = <String, Set<File>>{};
  for (final file in files) {
    final fileName = file.path.split(Platform.pathSeparator).last.split('.').first;
    final set = fileNameToExports[fileName] ?? <File>{};
    set.add(file);
    fileNameToExports[fileName] = set;
  }
  return fileNameToExports;
}

/// Write the exports to the new file
Future<void> _populateExports(Map<String, Iterable<File>> dirStructure) async {
  for (final entry in dirStructure.entries) {
    final files = _getFileStructure(entry.value);
    for (final fEntry in files.entries) {
      final file = File('$_newProtoPath${entry.key}${Platform.pathSeparator}${fEntry.key}.dart');
      await file.create(recursive: true);
      final writer = file.openWrite(mode: FileMode.writeOnlyAppend);
      writer.writeAll([
        '/// The proto definitions for ${fEntry.key}',
        '/// {@category Protobuf Definitions}',
        'library viam_protos.${entry.key}.${fEntry.key};\n',
        '// THIS FILE IS AUTOMATICALLY GENERATED',
        '// DO NOT OVERWRITE\n',
      ], '\n');
      for (final export in fEntry.value.sorted((a, b) => a.path.toString().compareTo(b.path.toString()))) {
        final relativeExport = path.relative(export.path, from: file.path);
        writer.writeln('export \'$relativeExport\';');
      }
      await writer.close();
    }
  }
}

Future<void> main(List<String> args) async {
  try {
    await Directory(_newProtoPath).delete(recursive: true);
  } on PathNotFoundException {
    // Don't actually need to do anything here
  }
  final files = await _getFiles();
  final dirNameToFiles = _getDirStructure(files);
  await _createDirs(dirNameToFiles.keys);
  await _populateExports(dirNameToFiles);
}
