/// The proto definitions for module
/// {@category Protobuf Definitions}
library viam_protos.module.module;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/module/v1/module.pbenum.dart';
export '../../../src/gen/module/v1/module.pb.dart';
export '../../../src/gen/module/v1/module.pbgrpc.dart';
export '../../../src/gen/module/v1/module.pbjson.dart';
