/// The proto definitions for agent
/// {@category Protobuf Definitions}
library viam_protos.app.agent;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/app/agent/v1/agent.pb.dart';
export '../../../src/gen/app/agent/v1/agent.pbenum.dart';
export '../../../src/gen/app/agent/v1/agent.pbgrpc.dart';
export '../../../src/gen/app/agent/v1/agent.pbjson.dart';
