/// The proto definitions for app
/// {@category Protobuf Definitions}
library viam_protos.app.app;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/app/v1/app.pbenum.dart';
export '../../../src/gen/app/v1/app.pbjson.dart';
export '../../../src/gen/app/v1/app.pb.dart';
export '../../../src/gen/app/v1/app.pbgrpc.dart';
