/// The proto definitions for billing
/// {@category Protobuf Definitions}
library viam_protos.app.billing;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/app/v1/billing.pb.dart';
export '../../../src/gen/app/v1/billing.pbenum.dart';
export '../../../src/gen/app/v1/billing.pbgrpc.dart';
export '../../../src/gen/app/v1/billing.pbjson.dart';
