/// The proto definitions for build
/// {@category Protobuf Definitions}
library viam_protos.app.build;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/app/build/v1/build.pb.dart';
export '../../../src/gen/app/build/v1/build.pbenum.dart';
export '../../../src/gen/app/build/v1/build.pbgrpc.dart';
export '../../../src/gen/app/build/v1/build.pbjson.dart';
