/// The proto definitions for data_pipelines
/// {@category Protobuf Definitions}
library viam_protos.app.data_pipelines;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/app/datapipelines/v1/data_pipelines.pb.dart';
export '../../../src/gen/app/datapipelines/v1/data_pipelines.pbenum.dart';
export '../../../src/gen/app/datapipelines/v1/data_pipelines.pbgrpc.dart';
export '../../../src/gen/app/datapipelines/v1/data_pipelines.pbjson.dart';
