/// The proto definitions for data
/// {@category Protobuf Definitions}
library viam_protos.app.data;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/app/data/v1/data.pbenum.dart';
export '../../../src/gen/app/data/v1/data.pb.dart';
export '../../../src/gen/app/data/v1/data.pbjson.dart';
export '../../../src/gen/app/data/v1/data.pbgrpc.dart';
