/// The proto definitions for data_sync
/// {@category Protobuf Definitions}
library viam_protos.app.data_sync;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/app/datasync/v1/data_sync.pb.dart';
export '../../../src/gen/app/datasync/v1/data_sync.pbenum.dart';
export '../../../src/gen/app/datasync/v1/data_sync.pbgrpc.dart';
export '../../../src/gen/app/datasync/v1/data_sync.pbjson.dart';
