/// The proto definitions for ml_inference
/// {@category Protobuf Definitions}
library viam_protos.app.ml_inference;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/app/mlinference/v1/ml_inference.pb.dart';
export '../../../src/gen/app/mlinference/v1/ml_inference.pbenum.dart';
export '../../../src/gen/app/mlinference/v1/ml_inference.pbgrpc.dart';
export '../../../src/gen/app/mlinference/v1/ml_inference.pbjson.dart';
