/// The proto definitions for ml_training
/// {@category Protobuf Definitions}
library viam_protos.app.ml_training;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/app/mltraining/v1/ml_training.pbenum.dart';
export '../../../src/gen/app/mltraining/v1/ml_training.pbgrpc.dart';
export '../../../src/gen/app/mltraining/v1/ml_training.pb.dart';
export '../../../src/gen/app/mltraining/v1/ml_training.pbjson.dart';
