/// The proto definitions for model
/// {@category Protobuf Definitions}
library viam_protos.app.model;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/app/model/v1/model.pbenum.dart';
export '../../../src/gen/app/model/v1/model.pbjson.dart';
export '../../../src/gen/app/model/v1/model.pb.dart';
export '../../../src/gen/app/model/v1/model.pbgrpc.dart';
