/// The proto definitions for packages
/// {@category Protobuf Definitions}
library viam_protos.app.packages;

// THIS FILE IS AUTOMATICALLY GENERATED
// DO NOT OVERWRITE
export '../../../src/gen/app/packages/v1/packages.pbjson.dart';
export '../../../src/gen/app/packages/v1/packages.pbgrpc.dart';
export '../../../src/gen/app/packages/v1/packages.pbenum.dart';
export '../../../src/gen/app/packages/v1/packages.pb.dart';
