name: Generate docs

on:
  workflow_dispatch:
  push:
    paths:
      - "lib/**"
      - "doc/**"
      - "README.md"
      - "dartdoc_options.yaml"
    branches: [main]

jobs:
  generate-docs:
    if: github.repository_owner == 'viamrobotics'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cirruslabs/flutter:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        run: flutter pub get

      - name: Generate docs
        run: dart doc

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/api
          publish_branch: docs-gh_pages
          cname: flutter.viam.dev

      - name: Zip artifacts
        run: zip html-docs.zip ./doc/api -r

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: html-docs.zip
