name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
            channel: 'stable'
            
      - run: flutter --version
      - run: flutter pub get
      - run: flutter pub get --directory=example/viam_example_app

      # Verify formatting in all dart files, except lib/gen/
      - name: Verify formatting
        run: dart format --line-length=140 --set-exit-if-changed $(find . -name "*.dart" -not -path "./lib/src/gen/*")

      - name: Analyze project source
        run: dart analyze --no-fatal-warnings

      - name: Run tests
        run: flutter test
